### ISSUE TITLE
About krakend

### ISSUE THREAD

**Issue by acanimal** [devopsfaith/krakend#1]
Hi, project seems really excited.
I'm thrilled to see the source code. Which programming language did you use?

It remembers a never ended project I started some time ago based on http-proxy: https://github.com/clydeio/clydeio/wiki/Introducing-Clyde

If I can contribute on any way let me know !!!

**Comment by friedcalamari** [comment]
Hi @acanimal!

We are very excited to see interest in the project, and having our first issue even without having published the code yet. It will be really soon, I promise.

I had a look at Clyde and this project goes in the same path, I am sure you are going to enjoy it. It is coded in go lang. Even if this is not a language you know (or want to learn) just by testing the product and using it it is the most simple way of contributing, and helps a lot. If you want to dig into the code, we will be more thank happy to review any pull requests.

Thanks for your interest!

**Comment by kpacha** [comment]
@acanimal, the code is already available.

enjoy!
