### ISSUE TITLE
FR: Configuration via API

### ISSUE THREAD

**Issue by leostarcevic** [devopsfaith/krakend#100]
I'd like to change the configuration via an API instead of loading and saving the configuration file (KrakenDesigner) or updating it manually to change/add endpoints. 

It would also allow developers to integrate docker swarm/kubernetes to automatically register endpoints by creating services.

**Comment by kpacha** [comment]
hi, @leostarcevic 

this is something people ask us a lot. I'll try to explain here the reason we have for not adding the feature (managing the service configuration and hot-swapping it without restarting the service):

- performance: the KrakenD gateway builds the pipes at starting time
- consistency: the api contract should be versioned
- simplicity: developing consistency strategies for distributing configuration updates in an ecosystem of independent, non-coordinated and state-less services like KrakenD is completely out of the scope of the project (without adding some restrictions that will make the feature less attractive and the system, very error-prune)

I think building a custom docker container with your own configuration and using the resultant image as the artifact to deploy is the proper and easier way to proceed.

On the other hand, the small size of the docker images and the footprint of the solution makes it easier to manage the running instancies by the config version they are using and just use a blue-green deploy strategy to release your changes.

cheers

**Comment by leostarcevic** [comment]
Hi!
> performance: the KrakenD gateway builds the pipes at starting time

This is a valid reason that I won't argue with. I understand the design choice. 👍 

> I think building a custom docker container with your own configuration and using the resultant image as the artifact to deploy is the proper and easier way to proceed.

Yeah, this was my other idea to run KrakenDesigner in a container and output the configuration file to a volume that Krakend mounts. It will be pretty easy to do when KrakenDesigner goes opensource.

**Comment by alombarte** [comment]
@leostarcevic Working on it right now

**Comment by leostarcevic** [comment]
We can close this ticket. Thanks for a fast answer!

**Comment by alombarte** [comment]
@leostarcevic https://github.com/devopsfaith/krakendesigner
