### ISSUE TITLE
Explicit header on partial responses

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/krakend#119]
We are currently relying on the cache headers to know if all the backends response completed (presence) or something failed (absence).

It could be helpful to include an explicit header to inform the client that the response is complete or not. 

Maybe something like `X-KrakenD-Completed: true|false` ?

It might add some unnecessary bytes but IMO is worth it.

**Comment by kpacha** [comment]
@alombarte should we add the header just to the successful responses or should be add it to all of them?

note: here, 'successful responses' are the ones the router is adding a 200 HTTP status code.

**Comment by alombarte** [comment]
All clients should rely on the existence of the header, whatever its content is. So, I would add the header in all cases.
