### ISSUE TITLE
DNS Lookup Config

### ISSUE THREAD

**Issue by tofftermattcirc** [devopsfaith/krakend#131]
I've been trying to get DNS working as I have a Consul instance running on another box for service discovery/lookup.

When I run the command
$dig +short jsonplaceholder.service.consul -p 8600
from the VM where KrakenD is deployed I get back:
https://jsonplaceholder.typicode.com/

Which is expected. I've tried many different values in the KrakenD config to get the DNS lookup to work like:
"hosts": [
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul"
      },
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul -p 8600"
      },
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul:8600"
      },
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul",
        "port":8600
      }
    ]

In the endpoints I've tried all combinations listed above as well as adding a 'port' key/value within the endpoint as well all without success.

Each time i try to make a REST call it comes back wtih

[GIN] 2018/05/03 - 17:49:40 | 500 |     130.601µs |   161.97.208.40 |  GET     /users
Error #01: no hosts available

Here's the full config file:
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    },
    "github_com/devopsfaith/krakend-etcd": {
      "dial_timeout": "5s",
      "dial_keepalive": "30s",
      "header_timeout": "1s"
    },
    "krakendesigner": {
      "endpoint_defaults": {
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0
        }
      }
    }
  },
  "sd_providers": {
    "providers": {
      "static": true,
      "dns": true
    },
    "hosts": [
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul"
      },
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul -p 8600"
      },
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul:8600"
      },
      {
        "sd": "dns",
        "host": "jsonplaceholder.service.consul",
        "port":8600
      }
    ]
  },
  "endpoints": [
    {
      "endpoint": "/users",
      "method": "GET",
      "concurrent_calls": 1,
      "extra_config": {
        "github_com/devopsfaith/krakend-httpsecure": {
          "disable": true,
          "allowed_hosts": [],
          "ssl_proxy_headers": {}
        },
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0
        }
      },
      "backend": [
        {
          "url_pattern": "/users",
          "extra_config": {
            "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
              "is_disabled": true,
              "endpoint_params": {}
            }
          },
          "encoding": "json",
          "sd": "dns",
          "host": [
            "jsonplaceholder.service.consul"
          ],
          "disable_host_sanitize": true,
          "is_collection": true,
          "target": "",
          "group": "users"
        }
      ]
    }
  ],
  "max_idle_connections": 250,
  "timeout": "3000ms",
  "read_timeout": "0s",
  "write_timeout": "0s",
  "idle_timeout": "0s",
  "read_header_timeout": "0s",
  "cache_ttl": "300s",
  "name": "test"
}

Thanks

**Comment by kpacha** [comment]
hi!

The DNS module is looking to the data returned from OS. Usually, it uses the standard DNS port (53).

Can you repeat the `dig` experiment but without the `-p` flag and asking for the SRV records (`$dig +short jsonplaceholder.service.consul SRV`)? If you get an empty response, try to configure `dnsmasq` as described in the consul documentation (https://www.consul.io/docs/guides/forwarding.html#dnsmasq-setup) before moving forward.

Once the test `$dig +short jsonplaceholder.service.consul SRV` works on the target VM, you can just add the service name `jsonplaceholder.service.consul` in your host list and the error should disappear.

cheers!

**Comment by alombarte** [comment]
Hi @tofftermattcirc ,

Just my two cents. It looks like you are struggling with setting up the service discovery. Before trying anything with Krakend you must get an IP when executing inside the machine `host jsonplaceholder.service.consul`. I would say that you need to review this `--dns=IP_ADDRESS` flag:

```
--dns=IP_ADDRESS...

Sets the IP addresses added as nameserver lines to the container's /etc/resolv.conf file. Processes in the container, when confronted with a hostname not in /etc/hosts, will connect to these IP addresses on port 53 looking for name resolution services.```

**Comment by tofftermattcirc** [comment]
Yes this is setting up a service discovery with Consul and the dns is working.

KrakenD is using correctly using Consul - i've modified the box's etc/resolv.conf

Notice when i do a 'dig +short jsonplaceholder.service.consul' via command line it resolves to "https://jsonplaceholder.typicode.com/"

Then problem is KrakenD is using "dig jsonplaceholder.service.consul **SRV**" which returns:
;; ANSWER SECTION:
jsonplaceholder.service.consul. 0 IN SRV 1 1 8080 jsonplaceholder.node.dc1.consul.
;; ADDITIONAL SECTION:
jsonplaceholder.node.dc1.consul. 0 IN CNAME https://jsonplaceholder.typicode.com/.

and KrakenD uses "Answer Section" and not the "Additional Section" and whether there's a setting to use the latter

**Comment by alombarte** [comment]
> and KrakenD uses "Answer Section" and not the "Additional Section" and whether there's a setting to use the latter
This is the expected behavior. The content to use must always be inside the answer section. IMO you should fix your setup to make `host -t SRV jsonplaceholder.service.consul` to return the right content in the answer section.

**Comment by taik0** [comment]
@tofftermattcirc you must use ip addresses (not names) in the `Address` field of the consul service or this behavior you are describing will happen.
As stated in the [RFC2782](https://www.ietf.org/rfc/rfc2782.txt):
>Target: There MUST be one or more address records for this name, the name MUST NOT be an alias

And you shouldn't add the https:// to the dns name.

Example using the same golang functions used in the dnssrv SD:
```vagrant@consulserver:~/test$ go run main.go
cname: jsonplaceholder.service.consul.
addr: acd912e5.addr.dc1.consul.:80
Lookup 172.217.18.229
addr: acd912e4.addr.dc1.consul.:80
Lookup 172.217.18.228```

In the end, the problem is that Consul allows to create invalid SRV records.
