### ISSUE TITLE
Add CORS adapter

### ISSUE THREAD

**Issue by kpacha** [devopsfaith/krakend#138]
As requested in https://github.com/devopsfaith/krakend-ce/issues/15, create a new adapter for a CORS middleware.

Here you have an example for the gin router: https://github.com/devopsfaith/krakend-examples/blob/master/jwt/main.go#L79

Here, a mux compatible handler: https://github.com/rs/cors

**Comment by taik0** [comment]
Added new CORS middleware: http://github.com/devopsfaith/krakend-cors

**Comment by kpacha** [comment]
done
