### ISSUE TITLE
Question: Edit host endpoint with middleware

### ISSUE THREAD

**Issue by Eywek** [devopsfaith/krakend#139]
Hello,

It is possible to edit host endpoint via a middleware ? I need to send the request on a specific backend depending on a ID send as parameter (MongoDB ID).

Thanks.

**Comment by alombarte** [comment]
Hey @Eywek, please make sure my assumptions are correct:

- You might want this for sharding
- You want to route something like  (a simple example):
   - `/foo/{mongo_id}` when `mongo_id=1 ` to `/shard-odd` 
   - `/foo/{mongo_id}` when `mongo_id=2` to `/shard-even`

If this is the case and **your sharding is not very complex** a first approach could be to create a route per shard. For instance, you would define the following endpoints in krakend:

- `/foo/shard-even/{mongo_id}` -> backend `/shard-even` 
- `/foo/shard-odd/{mongo_id}` -> backend `/shard-odd` 

Of course you would use something more suitable and less obvious than `shard-even` in the URL, but anything that is fixed and known will do the trick. With this example you would have 2 endpoints for the same functionality but it would work. It is assumed that if you have the `ID` when you call the Gateway you are in control to construct the right gateway URL pointing to will point to the right backend.

We have seen things like this in login providers for instance. But if this approach does not suit you or your case is more complex, or just want to delegate the logic to the gateway then you need to add a specific middleware for this.

This is totally doable and there are installs around that have their own similar cases.

**Comment by alombarte** [comment]
The `{mongo_id}` would be probably unnecessary in your case after doing the trick. But I left it in case you want to pass it as well

**Comment by Eywek** [comment]
In fact, I have to redirect each mongo id to a specific backend depending on what the mongo database returns me, so I can't create a route for each mongo id. 
So a middleware seems a good way, but I don't know how to edit which backend (host) Krakend need to call via this middleware. 
By default, if I don't have a mongo id in my request, I have to load balance my request to defined backends.

**Comment by alombarte** [comment]
Like in a service discovery?

**Comment by Eywek** [comment]
Hm, actually I have 6 servers which handle clients. Each client have a specific ID and I need to proxy theirs queries (from my front application) from https://my.app/api/<id>/... to https://specific-backend/api/<id>/..., the backend host is available in the user document (in mongodb). 
I've already found how to retrieve the user document with the ID parameter in the URL in a middleware but I don't see how I can edit on which endpoint Krakend will make the request.

**Comment by kpacha** [comment]
Hi @Eywek,

if you are blocking a request while waitting for a response from an external service/database, your gateway and your clients will be heavily impacted. I'd recommend you to select some deterministic way to select the backend and avoid sending extra queries through the network. Please, check this post for more on that topic: http://www.krakend.io/blog/what-is-an-api-gateway/

anyway, I can see some ways to implement a solution for your requirements:

### Quick way:

Build 6 private endpoints, each one connected to one of your backends. I guess their configuration will be identical, so you can use variables in your config files and avoid duplications. (https://github.com/devopsfaith/krakend-flexibleconfig/blob/master/template_test.go)

Build a single public endpoint using your custom middleware to edit the path (not the backend) of the request to be sent to localhost, and use the private endpoints declared above to do the actual data manipulation.

### Hard way:

Create a middleware that accepts N proxies and delegate the request to the one with the ID returned by your dictionary.

Here, the argument `f` represents the dictionary querying function

```
func Middleware(totalBackends int, f func(context.Context, *proxy.Request) (int, error)) proxy.Middleware {
	return func(next ...proxy.Proxy) proxy.Proxy {
		l:= len(next)
		switch {
		case l<totalBackends:
			panic(proxy.ErrNotEnoughProxies)
		case l>totalBackends:
			panic(proxy.ErrTooManyProxies)
		default:
		}

		errUnknownBackendID := errors.New("unknwon backend id")

		return func(ctx context.Context, request *proxy.Request) (*proxy.Response, error) {
			id, err := f(ctx, request)
			if err != nil {
				return nil, err
			}
			switch{
			case id<0:
				return nil, errUnknownBackendID
			case id>=len(next):
				return nil, errUnknownBackendID
			default:
			}
			return next[id](ctx, request)
		}
	}
}

func ProxyFactory(pf proxy.Factory, f func(context.Context, *proxy.Request) (int, error)) proxy.FactoryFunc {
	// check if the wrapper should be built or just return the received proxy factory
	// ...

	return func(cfg *config.EndpointConfig) (proxy.Proxy, error) {
		// extract backendDefinitions and the numberOfBackends from the config
		next := make([]proxy.Proxy, numberOfBackends)
		for i, backendDefinition := range backendDefinitions {
			p, err := pf.New(backendDefinition)
			if err != nil {
				panic(err)
			}
		}
		return Middleware(numberOfBackends, f)(next...), nil
	}
}
```

Check the [KrakenD-CE](https://github.com/devopsfaith/krakend-ce/blob/master/proxy_factory.go) for more on how to stack the cutsom factory in your KrakenD gateway.

Cheers!

**Comment by kpacha** [comment]
Hey! I have one more way to implement your requirements: using a custom martian modifier. :tada:

If your custom middleware does something like this:
```
func Middleware(totalBackends int, f func(context.Context, *proxy.Request) (int, error)) proxy.Middleware {
	return func(next ...proxy.Proxy) proxy.Proxy {
		switch len(next) {
		case 0:
			panic(proxy.ErrNotEnoughProxies)
		case 1:
		default:
			panic(proxy.ErrTooManyProxies)
		}

		errUnknownBackendID := errors.New("unknwon backend id")

		return func(ctx context.Context, request *proxy.Request) (*proxy.Response, error) {
			id, err := f(ctx, request)
			if err != nil {
				return nil, err
			}
			switch{
			case id<0:
				return nil, errUnknownBackendID
			case id>=totalBackends:
				return nil, errUnknownBackendID
			default:
			}
			request.Params[serverIDKey] = id
			return next[0](ctx, request)
		}
	}
}
```

 You can create a custom martian modifier using the [official one](https://github.com/google/martian/blob/master/martianurl/url_modifier.go) as a baseline. Here you have a post that will help you with the implementation and including it in your KrakenD gateway: http://www.krakend.io/blog/website-development-as-a-sysadmin/ .

 Cheers!

**Comment by Eywek** [comment]
It works! Thanks you! It was really useful!
