### ISSUE TITLE
Support for Flogo

### ISSUE THREAD

**Issue by roscopecoltran** [devopsfaith/krakend#147]
Hi guys,

Hope you are all well !

It would be awesome to have a support for [Flogo](https://github.com/TIBCOSoftware/flogo) and [Mashling](https://github.com/TIBCOSoftware/mashling). It would make easier to create flows and pipelines scenarios. It could embed the kraken designer as the flow webui is written with angularjs.

**Docker - Flogo web** 
- https://hub.docker.com/r/flogo/flogo-docker/
- https://github.com/retgits/dockerfiles/tree/master/flogoweb

**Flogo - Components**
- https://github.com/retgits/flogo-components/tree/master/activity
- https://github.com/TIBCOSoftware/flogo-contrib/tree/master/activity
- https://github.com/retgits/flogo-components/tree/master/trigger

**Flogo - Tools**
- https://github.com/retgits/fgen
- https://github.com/retgits/flogowebhelper

**Mashling:**
- https://github.com/TIBCOSoftware/mashling
- https://www.mashling.io/home

What do you think about that ? a basic example would be great ^^

Cheers,
Rosco

**Comment by alombarte** [comment]
Well, after two years this was expected :)

Jokes asides, we didn't receive any upvotes...
