### ISSUE TITLE
Support for Multi-Part inputs

### ISSUE THREAD

**Issue by roscopecoltran** [devopsfaith/krakend#148]
Hi guys,

Hope you are all well again !

It would be great to manage multi-part image(s) inputs for aggregating JSON results from machine learning based services.

Examples:
- https://github.com/tleyden/open-ocr
  - https://github.com/tleyden/open-ocr/blob/master/ocr_http_multipart_handler.go#L16
- https://github.com/jolibrain/deepdetect

Cheers,
Rosco

**Comment by kpacha** [comment]
Hi,

can you elaborate a little more? what should be the input format? do you want the request (a multipart form) to be also managed by the gateway?

thx for the ideas!!!

**Comment by kpacha** [comment]
@roscopecoltran I think this https://github.com/devopsfaith/krakend/pull/256 will help you adding your open-ocr implementation as a KrakenD plugin
