### ISSUE TITLE
Forwarding array[]-params through krakend not possible

### ISSUE THREAD

**Issue by Tobias-KW** [devopsfaith/krakend#149]
Forwarding params to a service via krakend not possible with array[]-params like ?order[]=123&order[]=456

**Used configuration**
Version 0.5 & Version 0.6
"querystring_params": ["order","order[]"],

**Expected result**
array(1) { 
     ["order"]=> array(2) { 
          [0]=> string(3) "123" 
          [1]=> string(3) "456"
 }
}

**Actual result**
array(1) {
 ["order"]=>
 array(1) {
   [0]=>
   string(3) "123"
 }
}

**Comment by taik0** [comment]
Hi @Tobias-KW the PR 151 should fix this issue.
