### ISSUE TITLE
support dynamic update proxy rules

### ISSUE THREAD

**Issue by rfyiamcool** [devopsfaith/krakend#166]
how to dynamic update config file in krakend , don't restart krakend ?

thank you.

**Comment by alombarte** [comment]
Hello @rfyiamcool ,
KrakenD creates the proxy pipes at startup time for performance reasons. If you change the configuration then the service must be restarted. There is a solution for this when you are in development through a wacher.

Here is our blog post on how to do it: https://www.krakend.io/blog/reloading-the-krakend-configuration/
