### ISSUE TITLE
500 internal server error in case of empty JSON response

### ISSUE THREAD

**Issue by MedElloumi** [devopsfaith/krakend#167]
Hello,

I just started my first krakend test and my first endpoint is the following:

```json
    {
      "endpoint": "/posts",
      "method": "GET",
      "output_encoding": "json",
      "concurrent_calls": 1,
      "extra_config": {},
      "backend": [
        {
          "url_pattern": "/posts",
          "encoding": "json",
          "extra_config": {
            "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
              "is_disabled": true,
              "endpoint_params": {}
            }
          },
          "sd": "static",
          "is_collection": true,
          "host": [
            "https://jsonplaceholder.typicode.com"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
```

everything is working as expected however when I change the url_pattern from /posts to /xx which is this link : https://jsonplaceholder.typicode.com/xx . {empty JSON object} I am receiving a 500 internal server error in my gateway !

**Comment by kpacha** [comment]
hi, @MedElloumi  and welcome to the KrakenD community!

Change the backend `is_collection` param because it is not what the backend service is returning (an empty object is not a collection) and everything should be fine.

Cheers!

**Comment by MedElloumi** [comment]
> hi, @MedElloumi and welcome to the KrakenD community!
> 
> Change the backend `is_collection` param because it is not what the backend service is returning (an empty object is not a collection) and everything should be fine.
> 
> Cheers!

Thank you @kpacha , I just tried to change it to false or remove the whole attribute but still the same result ...

**Comment by kpacha** [comment]
I'm removing the bug tag because it is not an actual formatter bug.

The backend is not just returning an empty object... it is returning a 404 error.

```
$ curl -i https://jsonplaceholder.typicode.com/xx
HTTP/2 404
date: Wed, 07 Nov 2018 16:42:33 GMT
content-type: application/json; charset=utf-8
content-length: 2
set-cookie: __cfduid=db3a6ce31bd10e848121fd5f1b72d9b061541608953; expires=Thu, 07-Nov-19 16:42:33 GMT; path=/; domain=.typicode.com; HttpOnly
x-powered-by: Express
vary: Origin, Accept-Encoding
access-control-allow-credentials: true
cache-control: public, max-age=14400
pragma: no-cache
expires: Wed, 07 Nov 2018 20:42:33 GMT
x-content-type-options: nosniff
etag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"
via: 1.1 vegur
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 476140f89e7e9c77-AMS

{}
```

**Comment by MedElloumi** [comment]
@kpacha Thank you a lot for debugging that, but I still think that the gateway should return the same result : {} and not a 500 internal server error ))

Cheers!

**Comment by kpacha** [comment]
you are welcome ;)

we are very proud of the product stability and we take very seriously every possible bug.

regarding the status code mapping, I think it's a matter of simplicity and security (when talking about api gateways).

- simplicity: it helps decoupling the client from the backends
- security: hardering the ecosystem behind the gateway

and it's already documented: https://www.krakend.io/docs/faq/#i-am-getting-a-500-status-when-the-backend-returns-anything-but-200-201-or-redirects

but we do not enforce that in the framework. as you can see, there is an interface for the status handler and several implementations available at https://github.com/devopsfaith/krakend/blob/master/transport/http/client/status.go

for no-op pipes (raw routing), the status code is passed as received cause no further manipulation of the data is required
