### ISSUE TITLE
[OAuth2] ClientId is being escaped

### ISSUE THREAD

**Issue by pushrbx** [devopsfaith/krakend#168]
I have the following clientId:
`celestal:readonly`
When krakend sends the request to the token endpoint, it escapes the `:`.
So the token endpoint receives `celestal%3Areadonly`.

How can I change this behaviour?

**Comment by taik0** [comment]
Hi @pushrbx the [oauth2 RFC](https://tools.ietf.org/html/rfc6749#section-2.3.1) states that the client identifier must be urlencoded. 
This is done automatically by the golang.org/x/oauth2 package.

**Comment by pushrbx** [comment]
Thanks. In the meantime I've discovered this too.
