### ISSUE TITLE
The best way to have own endpoint hosts for different environments.

### ISSUE THREAD

**Issue by vm-affekt** [devopsfaith/krakend#172]
Hello! I am planning to deploy my API Gateway app (KrakenD) to the Kubernetes. Each microservice has a string hostname (_e.g. http://my-service:2342_). I can set these hosts in config field **endpoint.hosts**. But I want to be able to test my gateway on a local machine before deploying it to the server. Since microservices can have only numeric IP-addresses on the local environment, I must have a separate list of hosts for this environment. 
What is the best way to do that? Notice that I want to use KrakenD as Golang library...
Thanks.

**Comment by kpacha** [comment]
hi @vm-affekt 

maybe you could use the [krakend-flexibleconfig](https://github.com/devopsfaith/krakend-flexibleconfig) pkg and define a different settings file for every environment.

you can also change those values programmatically depending on some flag... but that would be something you should add and maintain at your implementation.

best

**Comment by vm-affekt** [comment]
@kpacha Thank you for a fast reply!
