### ISSUE TITLE
Headers from Request are filtered Camel Case  

### ISSUE THREAD

**Issue by ricmoreira** [devopsfaith/krakend#176]
https://github.com/devopsfaith/krakend/blob/55df0681bda053f0af9838215edabf8510619fd5/router/gin/endpoint.go#L98

Could we replace this section by this? 

```
		for _, k := range headersToSend {
			if v := c.Request.Header.Get(k); v != "" {
				headers[k] = []string{v}
			}
		}
```
The way it's implemented causes a header like "X-SOMETHING" to be captured as "X-Something" because of it's filtering by the map structure. If we explicitly access the header from the Header.Get method, this problem will not occur.

**Comment by kpacha** [comment]
hi, @ricmoreira 

The `Get` method just returns the first value, not all of them

> Get gets the first value associated with the given key. It is case insensitive; textproto.CanonicalMIMEHeaderKey is used to canonicalize the provided key. If there are no values associated with the key, Get returns "". To access multiple values of a key, or to use non-canonical keys, access the map directly.

If what we want is more tolerance for the client requests, we can use the `textproto.CanonicalMIMEHeaderKey` (https://play.golang.org/p/niSmF8ob43x) for the lookup, but the backends will always get the header key as defined at the configuration.

```
		for _, k := range headersToSend {
			if h, ok := c.Request.Header[textproto.CanonicalMIMEHeaderKey(k)]; ok {
				headers[k] = h
			}
		}
```

I think this will be more flexible...

Will you create a PR?

**Comment by ricmoreira** [comment]
Yes @kpacha, I will. Thanks!
