### ISSUE TITLE
Can Krakend handle aggregation across multiple end points?

### ISSUE THREAD

**Issue by majuansari** [devopsfaith/krakend#182]
I want to aggregate the response served by api gateway. Is there any I could achieve that with Krakend ? 

Say if I have a gateway api  /api/home and which gets data from /api/user and /api/user/offers. I want to transform the response to something else before sending it back to client.

Can I do that with Krakend ?

**Comment by alombarte** [comment]
Hello @majuansari ,

Yes, you can do this with KrakenD. Aggregation of multiple sources is one of the key features.

With the following configuration example, you can see how the `/splash` endpoint is taking data from two different endpoints: `/shop/campaigns.json'  and `/shop/products.json`.

Additionally, in this example, you can see the `whitelist` section which is used to specify the only wanted attributes from the backend responses.

Check [response manipulation](https://www.krakend.io/docs/endpoints/response-manipulation/) in the docs for further information.

**Comment by majuansari** [comment]
Thanks @alombarte . Are there any talks or videos on Krakend ?

**Comment by alombarte** [comment]
No, we should start recording them...
