### ISSUE TITLE
Wild Card Redirection

### ISSUE THREAD

**Issue by majuansari** [devopsfaith/krakend#183]
Hi,

Once again thank you for this wonderful project :)

We are in process of migrating our monolith. We have 100's of routes and we don't want to put all these routes in config.json.

So i would like to have a config like this
`  "endpoints": [
    {
      "endpoint": "products/*",
      "method": "GET",
      "querystring_params" : ["*"],
      "backend": [
        {
          "url_pattern": "*",
          "host": [
            "http://prodcut.service:8001"
          ]
        }
      ]
    },
    {
      "endpoint": "store/*",
      "method": "GET",
      "querystring_params" : ["*"],
      "backend": [
        {
          "url_pattern": "*",
          "host": [
            "http://store.service:8002"
          ]
        }
      ]
    }
  ]`

With this say if I get a request https://gateway.service:8003/products/recomended should respond with http://product.service:8001/recomended 
and
https://gateway.service:8003/store/list  should respond with http://store.service:8002/list

Can I do this with Krakend ?

**Comment by kpacha** [comment]
hi, @majuansari 

The `*` wildcard is not supported, but there are ways to do something similar: I'd split the patterns depending on the number of parameters

```
{
	"endpoint": "/products/{param1}/{param2}",
	"querystring_params": ["*"],
	"backend": [{
		"url_pattern": "/{param1}/{param2}",
		"host": ["http://prodcut.service:8001"]
	}]
},
{
	"endpoint": "/products/{single_param}",
	"querystring_params": ["*"],
	"backend": [{
		"url_pattern": "/{single_param}",
		"host": ["http://prodcut.service:8001"]
	}]
},
{
	"endpoint": "/store/{param}",
	"querystring_params": ["*"],
	"backend": [{
		"url_pattern": "/{param}",
		"host": ["http://store.service:8002"]
	}]
}
```

cheers

**Comment by majuansari** [comment]
Thanks mate. I am extending mux.go and endpoint go and trying to handle this from code itself .

Your comments at https://github.com/devopsfaith/krakend/pull/141 also helped a lot.

**Comment by lindleywhite** [comment]
We had a use case where our wildcard was against a single service. So I modified gin's NoRoute handler to build a proxy at request time to service the dynamic request.
