### ISSUE TITLE
[Question] SOAP

### ISSUE THREAD

**Issue by MateoM24** [devopsfaith/krakend#187]
Hi,
Is it possible to use krakenD to get data from SOAP service and if so to combine results from it and REST services into single response?

**Comment by alombarte** [comment]
Hi @MateoM24 

Yes, it is entirely possible to use SOAP with KrakenD as it is an XML envelope. But for the open source version, we have not developed any specific component to facilitate its integration; neither we have plans to.

We have a condensed roadmap, and we try to include the features that make more sense today, but unfortunately, SOAP is not even present in the backlog.

We are aware that SOAP is still in use in legacy systems. The solution we can offer in this cases is only via Enterprise, but it doesn't make sense for us to put more complexity with this feature.
