### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by FerdinaKusumah** [devopsfaith/krakend#190]
How to implement basic auth to my backend ?

**Comment by kpacha** [comment]
hi @FerdinaKusumah , welcome to the KrakenD community.

Managing the auth at the gateway is not supported but it can be added, here you have a basic example: https://github.com/kpacha/krakend-http-auth

If your goal is to forward the `Authorization` header to the backend, you can add it to the `headers_to_pass` list (https://www.krakend.io/docs/endpoints/parameter-forwarding/#headers-forwarding)

Cheers!

**Comment by FerdinaKusumah** [comment]
the sctructure like this, i think
(A) -> (B) -> (C)
which is A is client, client doesnt do anything here just do http GET
B is krakend here
C is another backend

how B use http basic auth to get resource from C ?

**Comment by kpacha** [comment]
In that case, I'd use a martian header modifier in order to add the auth header to the requests to the backends.

Check this example: https://github.com/devopsfaith/krakend-ce/blob/master/krakend.json#L42_L53

**Comment by FerdinaKusumah** [comment]
{
    "version": 2,
    "name": "Traccar api middleware",
    "port": "9090",
    "extra_config": {
        "github_com/devopsfaith/krakend-httpsecure": {
            "allowed_hosts": [],
            "ssl_proxy_headers": {
                "X-Forwarded-Proto": "https"
            }
        },
        "github_com/devopsfaith/krakend-gologging": {
            "level": "INFO",
            "prefix": "[KRAKEND]",
            "syslog": false,
            "stdout": true
        },
        "github_com/devopsfaith/krakend-etcd": {
            "machines": ["http://localhost:4001"],
            "options": {
                "dial_timeout": "5s",
                "dial_keepalive": "30s",
                "header_timeout": "1s"
            }
        },
        "github_com/devopsfaith/krakend-metrics": {
            "listen_address": ":8090"
        },
        "github_com/devopsfaith/krakend-gelf": {
            "address": "localhost:8080",
            "enable_tcp": true
        },
        "github_com/devopsfaith/krakend-cors": {
            "allow_methods": [
                "GET",
                "HEAD",
                "POST",
                "PUT",
                "DELETE",
                "CONNECT",
                "OPTIONS",
                "TRACE",
                "PATCH"
            ],
            "allow_headers": ["Origin", "Authorization", "Content-Type"],
            "expose_headers": ["Content-Length"],
            "max_age": "12h"
        }
    },
    "timeout": "3000ms",
    "cache_ttl": "300s",
    "output_encoding": "json",
    "disable_rest": true,
    "idle_connection_timeout": "6000s",
    "response_header_timeout": "6000s",
    "expect_continue_timeout": "6000s",
    "max_idle_connections": "50",
    "max_idle_connections_per_host": "10",
    "disable_keep_alives": false,
    "endpoints": [{
            "endpoint": "/api/example",
            "method": "GET",
            "concurrent_calls": 1,
            "backend": [{
                "url_pattern": "/hello",
                "encoding": "json",
                "host": ["http://localhost:8080"]
            }]
        },
        {
            "endpoint": "/api/vehicles",
            "method": "GET",
            "concurrent_calls": 1,
            "querystring_params": ["uniqueId", "id"],
            "headers_to_pass": ["Authorization", "Content-Type", "accept"],
            "backend": [{
                "url_pattern": "/api/devices",
                "encoding": "json",
                "host": ["http://35.187.244.124:8082"]
            }],
            "extra_config": {
                "github.com/devopsfaith/krakend-ratelimit/juju/proxy": {
                    "maxRate": 1,
                    "capacity": 10
                },
                "github.com/devopsfaith/krakend-circuitbreaker/gobreaker": {
                    "interval": 60,
                    "timeout": 10,
                    "maxErrors": 5
                },
                "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
                    "username": "admin",
                    "password": "admin"
                },
                "github.com/devopsfaith/krakend-martian": {
                    "fifo.Group": {
                        "scope": ["request", "response"],
                        "aggregateErrors": true,
                        "modifiers": [{
                            "header.Modifier": {
                                "scope": ["request", "response"],
                                "name": "Authorization",
                                "value": "Basic YWRtaW46YWRtaW4="
                            }
                        }]
                    }
                }
            }
        },
        {
            "endpoint": "/api/vehicles",
            "method": "POST",
            "concurrent_calls": 1,
            "headers_to_pass": ["Authorization", "Content-Type", "accept"],
            "backend": [{
                "url_pattern": "/api/devices",
                "encoding": "json",
                "host": ["http://35.187.244.124:8082"]
            }],
            "extra_config": {
                "github.com/devopsfaith/krakend-ratelimit/juju/proxy": {
                    "maxRate": 1,
                    "capacity": 10
                },
                "github.com/devopsfaith/krakend-circuitbreaker/gobreaker": {
                    "interval": 60,
                    "timeout": 10,
                    "maxErrors": 5
                },
                "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
                    "client_id": "admin",
                    "client_secret": "admin"
                }
            }
        },
        {
            "endpoint": "/api/vehicles/{id}",
            "method": "PUT",
            "concurrent_calls": 1,
            "headers_to_pass": ["Authorization", "Content-Type", "accept"],
            "backend": [{
                "url_pattern": "/api/devices",
                "encoding": "json",
                "host": ["http://35.187.244.124:8082"]
            }],
            "extra_config": {
                "github.com/devopsfaith/krakend-ratelimit/juju/proxy": {
                    "maxRate": 1,
                    "capacity": 10
                },
                "github.com/devopsfaith/krakend-circuitbreaker/gobreaker": {
                    "interval": 60,
                    "timeout": 10,
                    "maxErrors": 5
                },
                "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
                    "client_id": "admin",
                    "client_secret": "admin"
                }
            }
        },
        {
            "endpoint": "/api/vehicles/{id}",
            "method": "DELETE",
            "concurrent_calls": 1,
            "headers_to_pass": ["Authorization", "Content-Type", "accept"],
            "backend": [{
                "url_pattern": "/api/devices",
                "encoding": "json",
                "host": ["http://35.187.244.124:8082"]
            }],
            "extra_config": {
                "github.com/devopsfaith/krakend-ratelimit/juju/proxy": {
                    "maxRate": 1,
                    "capacity": 10
                },
                "github.com/devopsfaith/krakend-circuitbreaker/gobreaker": {
                    "interval": 60,
                    "timeout": 10,
                    "maxErrors": 5
                },
                "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
                    "client_id": "admin",
                    "client_secret": "admin"
                }
            }
        }
    ]
}


whats wrong in my code ?
im sorry im new in krakenD
:)

**Comment by kpacha** [comment]
@FerdinaKusumah the martian modifiers apply to the backend components, so the extra_config should be placed at the backend level.

Please, try again with this endpoint definition:
```
{
	"endpoint": "/api/vehicles",
	"querystring_params": ["uniqueId", "id"],
	"headers_to_pass": ["Authorization", "Content-Type", "accept"],
	"backend": [{
		"url_pattern": "/api/devices",
		"host": ["http://35.187.244.124:8082"],
		"extra_config": {
			"github.com/devopsfaith/krakend-martian": {
				"fifo.Group": {
					"scope": ["request", "response"],
					"aggregateErrors": true,
					"modifiers": [{
						"header.Modifier": {
							"scope": ["request", "response"],
							"name": "Authorization",
							"value": "Basic YWRtaW46YWRtaW4="
						}
					}]
				}
			}
		}
	}]
}
```

Are you using the [KrakenDesigner](https://designer.krakend.io)?

**Comment by FerdinaKusumah** [comment]
`{
    "version": 2,
    "name": "api middleware",
    "port": "9090",
    "endpoints": [{
            "endpoint": "/api/example",
            "method": "GET",
            "concurrent_calls": 1,
            "headers_to_pass": ["Authorization", "Content-Type", "Accept"],
            "backend": [{
                "url_pattern": "/hello",
                "encoding": "json",
                "host": ["http://localhost:8080"]
            }]
        },
        {
            "endpoint": "/api/vehicles",
            "querystring_params": ["uniqueId", "id"],
            "headers_to_pass": ["Authorization", "Content-Type", "accept"],
            "backend": [{
                "url_pattern": "/api/devices",
                "host": ["http://35.187.244.124:8082"],
                "extra_config": {
                    "github.com/devopsfaith/krakend-martian": {
                        "fifo.Group": {
                            "scope": ["request", "response"],
                            "aggregateErrors": true,
                            "modifiers": [{
                                "header.Modifier": {
                                    "scope": ["request", "response"],
                                    "name": "Authorization",
                                    "value": "Basic YWRtaW46YWRtaW4="
                                }
                            }]
                        }
                    }
                }
            }]
        }
    ]
}`

i still cant use this config, event with this simple config 😓
yes I use it, maybe I put the code wrong earlier

**Comment by kpacha** [comment]
It's weird, because the extra_config for the martian modifier was misplaced and there are some values with wrong format (like `port`)

anyway, after replacing the backend call to be directed to the debug endpoint, I tested your config and it worked...

```
{
	"version": 2,
	"name": "api middleware",
	"port": 8000,
	"endpoints": [{
		"endpoint": "/api/example",
		"headers_to_pass": ["Authorization", "Content-Type", "Accept"],
		"backend": [{
			"url_pattern": "/__debug",
			"host": ["http://localhost:8000"]
		}]
	}, {
		"endpoint": "/api/vehicles",
		"querystring_params": ["uniqueId", "id"],
		"headers_to_pass": ["Authorization", "Content-Type", "accept"],
		"backend": [{
			"url_pattern": "/__debug",
			"host": ["http://localhost:8000"],
			"extra_config": {
				"github.com/devopsfaith/krakend-martian": {
					"fifo.Group": {
						"scope": ["request", "response"],
						"aggregateErrors": true,
						"modifiers": [{
							"header.Modifier": {
								"scope": ["request", "response"],
								"name": "Authorization",
								"value": "Basic YWRtaW46YWRtaW4="
							}
						}]
					}
				}
			}
		}]
	}]
}
```

request (notice it is returning the response given by the debug endpoint):
```
$ curl -i localhost:8000/api/vehicles
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Krakend: Version 0.7.1
X-Krakend-Completed: true
Date: Mon, 28 Jan 2019 15:02:49 GMT
Content-Length: 18

{"message":"pong"}
```

log:
```
[GIN-debug] redirecting request 301: /__debug --> /__debug/
 DEBUG: Method: GET
 DEBUG: URL: /__debug/
 DEBUG: Query: map[]
 DEBUG: Params: [{param /}]
 DEBUG: Headers: map[Referer:[http://localhost:8000/__debug] X-Forwarded-For:[::1] Accept-Encoding:[gzip] User-Agent:[KrakenD Version 0.7.1] Authorization:[Basic YWRtaW46YWRtaW4=]]
 DEBUG: Body:
[GIN] 2019/01/28 - 16:02:49 | 200 |     149.092µs |             ::1 | GET      /__debug/
[GIN] 2019/01/28 - 16:02:49 | 200 |    1.544872ms |             ::1 | GET      /api/vehicles
```

**Comment by FerdinaKusumah** [comment]
ok, but how can i debug response from server.
i means like print all request message from server ?

**Comment by kpacha** [comment]
inspecting/dumping the requests/responses is not possible out of the box. But we have several modules for that, like [krakend-spew](https://github.com/devopsfaith/krakend-spew)

I'd suggest you to start by just sending a curl request to your backends with the data dumped at the debug endpoint log.

```
curl -i -H'X-Forwarded-For: ::1' -H'Accept-Encoding: gzip' -H'User-Agent: KrakenD Version 0.7.1' -H'Authorization: Basic YWRtaW46YWRtaW4=' http://35.187.244.124:8082/api/devices
```

**Comment by FerdinaKusumah** [comment]
if I do that the server will respond to the data properly and correctly

**Comment by FerdinaKusumah** [comment]
can you give some example to test that route ?
thank you
