### ISSUE TITLE
AMQP protocol support?

### ISSUE THREAD

**Issue by janwebdev** [devopsfaith/krakend#204]
Hello, thanks for your job and the great platform!
I have a question (may be labeled new feature).
Is there planned support for AMQP protocol in KrakenD?
I can see in overview 

> Adding transport layer adapters for other protocols (Thrift, gRPC, AMQP, NATS, etc) is in the roadmap.

If yes, what are the terms of impletenting it? ;)

**Comment by alombarte** [comment]
Hi @janwebdev, thanks for your kind words.

We are currently working with gRPC. The AMQP protocol can be added without a problem, but I cannot give you a date for the open source version just yet. We plan the next releases every 3 months, and everything out the planned development falls under KrakenD Enterprise development. If you are interested in us coding AMQP for you send us an email to support AT devops.faith

Thanks

**Comment by kpacha** [comment]
@janwebdev , we've just released the https://github.com/devopsfaith/krakend-amqp module.

It's not well documented yet (and of course, it won't be integrated into the CE without some extra polishing work), but I hope you'll find it useful

enjoy the KrakenD!!!
