### ISSUE TITLE
JSON POST to Backend Service

### ISSUE THREAD

**Issue by db3net** [devopsfaith/krakend#211]
This might be a lack of my understanding, but I have a series of backend services that respond to POSTs with a JSON payload. In some cases these are static which allows a GET to the gateway to trigger a POST to the backend. In other cases, I want to collect the POST data at the gateway and pass the variables into a JSON payload for the backend post.

I can't seem to understand how to do this or if it's possible. It feels like there should be an option in the designer for the backend where one can select "JSON" and have a payload text-area where you can create a JSON payload with the variable replacement {vars}.

**Comment by db3net** [comment]
<img width="415" alt="Screen Shot 2019-03-12 at 12 45 04 PM" src="https://user-images.githubusercontent.com/7472095/54218861-bc016e80-44c4-11e9-865b-716d85f1ad66.png">
<img width="477" alt="Screen Shot 2019-03-12 at 12 44 59 PM" src="https://user-images.githubusercontent.com/7472095/54218862-bc016e80-44c4-11e9-89fe-5aea150183b9.png">

**Comment by Michael2008S** [comment]
I need this feature too .  #212

**Comment by alombarte** [comment]
Thank you @db3net for the detailed documentation.

I am leaving this issue open while we think about it. Meanwhile, we have also created an issue in  https://github.com/devopsfaith/krakendesigner/issues/51 as the graphical interface doesn't let you use different methods and this is not the reality for the server.

Thanks

**Comment by db3net** [comment]
Thanks. This is awesome.
