### ISSUE TITLE
Merging the 'Post' request with same json payload

### ISSUE THREAD

**Issue by Michael2008S** [devopsfaith/krakend#214]
I want to merging the 'Post' request from two backend 'post' api.

And I found that I can't do that Because : 
```go 
func (r httpRouter) registerKrakendEndpoint(method, path string, handler http.HandlerFunc, totBackends int) {
	method = strings.ToTitle(method)
	if method != http.MethodGet && totBackends > 1 {
		r.cfg.Logger.Error(method, "endpoints must have a single backend! Ignoring", path)
		return
	}
``` 
Is that a bad idea to allow the POST request merging?

**Comment by kpacha** [comment]
hi, @Michael2008S 

please, check my comment at https://github.com/devopsfaith/krakend/issues/194#issuecomment-460470842

**Comment by Michael2008S** [comment]
@kpacha  Thanks
