### ISSUE TITLE
[Question] BFF

### ISSUE THREAD

**Issue by chess-equality** [devopsfaith/krakend#215]
How to implement BFF ("Backends for Frontends") pattern with KrakenD?
Thanks.

**Comment by Michael2008S** [comment]
@chess-equality 
What does your supposed BFF look like?

**Comment by chess-equality** [comment]
@Michael2008S Currently we have a web and hybrid mobile BFF (in that order), later on we'll add a SPA BFF as well.

**Comment by alombarte** [comment]
Hi @chess-equality,

Thanks for introducing this question, it's probably too broad and is more for a blog post than an issue itself. I'll try to give you a short answer to your question, answering to what I think is your "HOW" and from here feel free to introduce more specific questions.

The Backend for Frontend architecture is usually used to create client facing applications such as the mobile applications, desktop apps or the website itself to name a few. Our recommendation is to create always a different krakend configuration for each client. For instance, you could have the following KrakenD configurations (and running servers) using your example:

- The iOS BFF (`krakend-ios.json`)
- Android BFF (`krakend-android.json`)
- Web BFF (`krakend-web.json`)
- SPA BFF (`krakend-spa.json`)

Depending on the size of your APIs you could, of course, have a single `krakend.json` supporting all endpoints across the clients, for instance, you could have one krakend configuration file with endpoints like this:

- `/ios/v1/products`
- `/android/v1/products`
- `/web/v1/landing`
- `/spa/v1/account`

I don't recommend this latter option as you have a service that is managed by different people with different needs and responsibilities.

KrakenD offers you an easy way to define the client contract that you can preserve while the backend keeps evolving. Implementing the BFF pattern is as simple as thinking what the API you want to offer for each client is, and write the configuration for it.

Hope this helps you.

**Comment by chess-equality** [comment]
@alombarte Thank you.
