### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by sandeep540** [devopsfaith/krakend#216]
I am getting the below error

```
[GIN] 2019/03/14 - 20:18:19 | 500 |    575.5341ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:47 | 500 |     71.7053ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:51 | 500 |     61.2667ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:51 | 500 |     61.4189ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:52 | 500 |     63.5494ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:53 | 500 |     59.9944ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:53 | 500 |     64.9002ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
[GIN] 2019/03/14 - 20:18:53 | 500 |     81.6292ms |      172.17.0.1 | GET      /styles
Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}
```
Any idea

**Comment by kpacha** [comment]
hi @sandeep540 and welcome to the KrakenD community!

based on the error you are getting, it looks like your backend is returning an array and you have not inform the decoder it should expect a collection.

doc: 
- https://www.krakend.io/docs/faq/#solution-to-invalid-responses
- https://www.krakend.io/docs/endpoints/response-manipulation/#collections-or-arrays

cheers!

**Comment by tiagovbarreto** [comment]
Hi friend, 
you must pass the parameter "is_collection": true in the backend of you endpoint. See documentation: https://www.krakend.io/docs/backends/data-manipulation/#collections

See you.

**Comment by iamabhishekmaurya** [comment]
`{
            "endpoint": "/view/depart",
            "backend": [
                {
                    **"is_collection": true,** // Use this in your code
                    "url_pattern": "/view/department"
                }
            ]
        },`

**Comment by iamabhishekmaurya** [comment]
{
            "endpoint": "/view/depart",
            "backend": [
                {
                    **"is_collection": true,** // use this one
                    "url_pattern": "/view/department"
                }
            ]
        },

**Comment by Anbool** [comment]
Thanks for the question, thanks for the developer's help, I also encountered this problem, and now it has been successfully solved.

**Comment by jackz7** [comment]
take a look at  

https://stackoverflow.com/questions/71476560/json-cannot-unmarshal-object-into-go-value-of-type-interface/71476792?noredirect=1#comment126334942_71476792
