### ISSUE TITLE
manipulation on arrays

### ISSUE THREAD

**Issue by gokcesurenkok** [devopsfaith/krakend#227]
that would be great :)

**Comment by alperhankendi** [comment]
indeed, that kind of feature may apply to just response manipulation but I'm not sure how impacts performance.  Is there any workaround or an alternative solution?

**Comment by kpacha** [comment]
we pushed a branch including a formatter using the [flatmap](https://github.com/devopsfaith/flatmap) lib: https://github.com/devopsfaith/krakend/tree/flatmap_formatter

the current implementation has a huge impact on the performance (between x3 and x4) so we don't think it's ready to be merged

**Comment by alperhankendi** [comment]
@kpacha  thanks for your quick reply. I've checked code it seems that imp will work only if u add flatmap to config so the default behavior won't impact on the performance

**Comment by gokcesurenkok** [comment]
thanks for the merge , will you be able to release it soon ? i deployed krakend in our kubernetes cluster , so i need the docker image to be able to redeploy with this feature.

**Comment by kpacha** [comment]
@gokcesurenkok : krakend 0.9.0 released
