### ISSUE TITLE
[Question] Adding params

### ISSUE THREAD

**Issue by KaelBaldwin** [devopsfaith/krakend#228]
I'm in a situation where I was hoping to use Krakend with key auth.

Our keys tie to a user id and one of our api endpoints requires that user id to be in the path.

So first I wrote a little middleware to handle the api_key and grab a user_id.

Now I need to make it an output parameter so it can be dynamically added to the url, so I handled adding that to the proxy before it goes to the backend.

I'm not really sure if that would have worked or not however as once I tried to start everything to test it out, I started getting errors about there being an unequal amount of input parameters and output parameters in the configuration.

Is there a better way to accomplish what I'm trying to do? and if not, is there any reason why the input / output parameter count needs to be locked down to being the same?

Thank you!

**Comment by KaelBaldwin** [comment]
Also I tried to join your slack via the link on github, but it just took me to their login page instead of letting me request an invite or something.

**Comment by KaelBaldwin** [comment]
We're going to try to move to generating a JWT containing that information instead and passing along that instead, but I'm still curious.

**Comment by kpacha** [comment]
hi @KaelBaldwin and welcome to the KrakenD community!!!

1. here you have the link to the slack invite form: https://invite.slack.golangbridge.org/
2. the number of input and output params are checked in order to be sure every param is properly mapped from an input to an output.
3. JWT does support passing this kind of details. You can also use the CEL module for adding custom verifiers

cheers!

**Comment by KaelBaldwin** [comment]
Thanks @kpacha!

To explain a little better what I was needing is that our backend has a url path like this:

/user/{user_id}/object/{object_id}

We assign specific api_keys tied to each user.

The user calls something like this: /object/{object_id}?api_key={api_key}

I'm needing to find the user_id tied to the provided api_key and use that user_id in backend path.

As new users are being added and removed every day, I don't believe the CEL module provides addresses that use case?

**Comment by kpacha** [comment]
notice that querystring params are optional and you expect your clients to always send the `api_key`...

maybe you can expose the endpoint `/object/{object_id}`, mapped to `/object/{object_id}` and require a JWT. The JWT validation can include a CEL expression looking for the existence of the `user_id` claim in the token.

Finally, you can extract the `user_id` claim from the JWT and append `/user/{user_id}` to the request path in a martian modifier (so the final path will be `/user/{user_id}/object/{object_id}` ).

**Comment by KaelBaldwin** [comment]
At this point we can't require our clients to change to using JWT's at this time, so we're going to have to do that for them I think.

My current plan is to add a proxy that uses that makes sure the api_key query param exists, and sends a request to another backend that will take that api_key and respond with the user_id and attach it to a header.

We'll change the backends to look for that header's value instead of looking for it in the path.

Thank you for your help!
