### ISSUE TITLE
How to prevent "Transfer-Encoding: chunked"

### ISSUE THREAD

**Issue by madzia912** [devopsfaith/krakend#234]
Hi,
I am implementing an application where KrakenD is used as a gateway. I am trying to make it work to integrate with a .NET Web API service, but the POST body received at the service is empty. After thorough investigation I came to the conclusion that it is related to the way POST body is being forwarded by krakenD - krakenD sends it with "Transfer-Encoding: chunked", which .NET has problems with handling (could be a [bug ](https://stackoverflow.com/questions/26111850/asp-net-web-api-the-framework-is-not-converting-json-to-object-when-using-chun) in .NET). 

I have tried different strategies to prevent krakenD from sending POST body with "Transfer-Encoding: chunked", which is e.g.:
- forwarding all the headers
- different combinations between "no-op" encoding and "json",
- disabling compression.

Do you know how we could achieve that krakenD sends the body not in a "chunked" way?

My latest configuration file:
[configuration.zip](https://github.com/devopsfaith/krakend/files/3029602/configuration.zip)

Thanks in advance!

**Comment by kpacha** [comment]
hi @madzia912 and welcome to the KrakenD community!

can you share the request you're sending to the gateway? I've been trying to reproduce it without success. also, does the direct request to the backend succeed?

By the way, the encoding is just related to the response body. the request body always hits the backend as received

Cheers!

**Comment by madzia912** [comment]
Hi @kpacha and thanks a lot for quick response!
The request body looks like below:

`{
	"cpr":"0101005208"
}`

The request to the backend succeeds without any problems. See attached sessions from Fiddler, where I call the service directly and via KrakenD. I have deployed a test service **http://krakend-stub-test.azurewebsites.net** - you can use it to reproduce the issue.

Let me know if you need any more information :)
[Krakend Issue.zip](https://github.com/devopsfaith/krakend/files/3033124/Krakend.Issue.zip)

**Comment by kpacha** [comment]
the fix is already in master, so it will be included into the next release

thanks!

**Comment by madzia912** [comment]
Awesome! :)

**Comment by madzia912** [comment]
@kpacha what is the ETA of next release of KrakenD? :)

**Comment by alombarte** [comment]
Good news @madzia912, we are doing it this week :)

**Comment by ionutzp** [comment]
any updates on this? just spent 5 hours tracking this to an issue in rails/rack/puma :)

**Comment by kpacha** [comment]
the last 2 releases already included the fix #235

**Comment by ionutzp** [comment]
thanks @kpacha for the fast answer, is there a way to not use *chunked* transfer with krakend?
