### ISSUE TITLE
Cannot use generated token in a subsequent call

### ISSUE THREAD

**Issue by bsloeserwij** [devopsfaith/krakend#237]
Thank you for this great project. 

We are trying to build an api gateway in front of a CMDBuild server. For interaction with this server through the API a token has to be generated. This can be done by the following command.

`curl --header 'Content-Type: application/json' --request POST --data-binary '{"username": "dummyuser", "password": "thisisasecurepassword"}' http://cmdbuild.example.com:8080/cmdbuild//services/rest/v2/sessions --verbose
`
which gives a output comparable to:

```
* About to connect() to cmdbuild.example.com port 8080 (#0)
*   Trying xxx.xxx.xxx.xxx...
* Connected to cmdbuild.example.com (xxx.xxx.xxx.xxx) port 8080 (#0)
> POST /cmdbuild/services/rest/v2/sessions HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cmdbuild.example.com:8080
> Accept: */*
> Content-Type: application/json
> Content-Length: 62
>
* upload completely sent off: 62 out of 62 bytes
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Date: Thu, 04 Apr 2019 07:51:49 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
<
* Connection #0 to host cmdbuild.example.com left intact
{"data":{"username":"dummyuser","role":"xxxx","availableRoles":["xxxx"],"_id":"1v02258o530kpotbfa1uklvam8"}}
```

Using the _id field information can be requested from the server:

`curl -v --header 'Content-Type: application/json' --header 'CMDBuild-Authorization: 1v02258o530kpotbfa1uklvam8' "http://cmdbuild.example.com:8080/cmdbuild/services/rest/v2/classes/example/cards"`

Which outputs a large json with information.

We want to use krakend to create a single api endpoint, which generates a token at the CMDBuild server and request the information. The output of this endpoint has to be the large json of the second command. To visualize is:

```
                  http://cmdbuild.example.com:8080/cmdbuild//services/rest/v2/sessions
     GET        /POST
User --> Krakend
                \GET                               
                  http://cmdbuild.example.com:8080/cmdbuild/services/rest/v2/classes/example/cards
```

We have tried to accomplish this with krakend, but with no success. We were able to generate the token, but it seems not possible to use the value of the token in a next call.

Is this a scenario which can be possible with krakend?

Thanks in advance.

**Comment by kpacha** [comment]
hi @bsloeserwij and welcome to the KrakenD community!

KrakenD supports sequential requests and these can have methods other than `GET`, but since they share the request body reader, they can not have a body. So, even if this config is correct (ignoring the fact we are placing the `_id` param into the url instead of into the required header)

```
{
    "endpoint": "/issue237",
    "headers_to_pass": ["*"],
    "extra_config": {
        "github.com/devopsfaith/krakend/proxy": {
            "sequential": true
        }
    },
    "backend": [
        {
            "host": ["http://cmdbuild.example.com:8080"],
            "method":"POST",
            "url_pattern": "/cmdbuild/services/rest/v2/sessions",
            "target": "data",
            "whitelist": ["_id"]
        },
        {
            "host": ["http://cmdbuild.example.com:8080"],
            "url_pattern": "/cmdbuild/services/rest/v2/classes/example/cards/{resp0__id}",
            "is_collection": true,
            "mapping": {
                "collection": "cards"
            }
        }
    ]
},
```

If you try to add something in the request body, the second request of the sequence will fail with this error:

```
Get http://cmdbuild.example.com:8080/cmdbuild/services/rest/v2/classes/example/cards/1v02258o530kpotbfa1uklvam8: http: invalid Read on closed Body
```
Also, KrakenD does not support mapping response values into the next request headers without some external help from a martian modifier.

So I'd suggest you to just create a martian modifier able to pause the request to the backend, negotiate a token and resume the operation once the obtained token is added into the request headers. Here, an initial example using the static header modifier already available out of the box:
```
{
    "endpoint": "/issue237",
    "headers_to_pass": ["*"],
    "backend": [
        {
            "host": [
                "http://cmdbuild.example.com:8080"
            ],
            "url_pattern": "/cmdbuild/services/rest/v2/classes/example/cards",
            "is_collection": true,
            "mapping": {
                "collection": "cards"
            },
            "extra_config": {
                "github.com/devopsfaith/krakend-martian": {
                    "fifo.Group": {
                        "scope": ["request", "response"],
                        "aggregateErrors": true,
                        "modifiers": [
                        {
                            "header.Modifier": {
                                "scope": ["request"],
                                "name" : "CMDBuild-Authorization",
                                "value" : "1v02258o530kpotbfa1uklvam8"
                            }
                        }
                        ]
                    }
                }
            }
        }
    ]
},
```
You can use the code of that modifier ([header.Modifier](https://github.com/google/martian/blob/master/header/header_modifier.go)) as base for your custom modifier and include the logic required for the token negotiation and request decoration (adding the header and a new body)

Cheers!

**Comment by bsloeserwij** [comment]
Hi @kpacha ,

Thank you for your reply. 
We managed to create a martian modifier to generate the token and set it as a header to the backend of the endpoint.
When KrakenD starts, we notice that the modifiers are parsed. In our case, the token is requested from the server when KrakenD is started. 
Due to this the workflow will be:

```
                token request
                /
krakend --> start --> user is allowed to do API calls
```

The following problems will occur with this workflow: 
  - When the token expires, no API calls can be done, until the KrakenD server is restarted.
  - The token can not be deleted from the server, which will not work from a security perspective.

We will not have these problems when we have a following workflow:

```
                             token request
                             /
API call from user --> Krakend - GET information
                             \
                             delete token from server
```

Is it possible to create a workflow like the one above? 

Thanks in advance.

**Comment by kpacha** [comment]
@bsloeserwij why don't you manage the token lifecycle from the modifier itself?

it could negotiate a token as soon as the first modifier is built and launch a goroutine dealing with the token refresh/renew. This would make the entire authentication process transparent for the customers and the operators

maybe you could use the golang.org/x/oauth2/internal package as an inspiration

**Comment by kpacha** [comment]
@bsloeserwij I think this will help you a lot: https://github.com/devopsfaith/krakend/pull/255 

you can create a plugin and attach it to your gateway without re-compiling the KrakenD
