### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by bstichter** [devopsfaith/krakend#240]
I know this issue is way outside of what is normal for an issue submission, but I've been looking at the KrakenD code for all of 5 minutes and it's my first time even looking at Go, but I think this debug line is incorrect.

https://github.com/devopsfaith/krakend/blob/1d20c1916774358fb9a86726f1e9633e133c5b90/config/config.go#L422

```
if outputSetSize > len(inputParams) {
  return fmt.Errorf("Too many output params! input: %v, output: %v\n", outputSet, outputParams)
}
```

The if statement is (basically) comparing `outputSet` and `inputParams`.  The message claims to print input and output.  Unfortunately, it prints outputParams, not inputParams.  Based on the context it seems the error message should be printing inputParams first and outputSet second instead of what it's printing?

**Comment by kpacha** [comment]
hi @bstichter and welcome to the KrakenD community!

you're 100% right. I opened a PR with the fix.

Thanks!!!
