### ISSUE TITLE
Cannot drag-drog to load configuration in ubuntu 16.04

### ISSUE THREAD

**Issue by DucVuMinh** [devopsfaith/krakend#243]
I try to reload configuration file in ubuntu from designer.krakend.io. But it does not work. It just opens file in browser instead of loading.

**Comment by alombarte** [comment]
Thanks for reporting @DucVuMinh, the issue is still pending of resolution. Please follow https://github.com/devopsfaith/krakendesigner/issues/43

**Comment by alombarte** [comment]
@DucVuMinh This should be fixed now
