### ISSUE TITLE
How to use JWT token payload to modify headers

### ISSUE THREAD

**Issue by kirinse** [devopsfaith/krakend#244]
Thank you for this great project.

We are trying to add a header "X-Auth" value: JWT.sub after JWT validate, send it to backend, but no luck. 

any suggestion/advice to achieve this? 

thanks.

**Comment by kpacha** [comment]
hi @kirinse and welcome to the KrakenD community!

There is no direct way to do what you described without adding a custom [martian modifier](https://github.com/devopsfaith/krakend-martian/). My initial suggestion would be to add `Authorization` to the set of `headers_to_pass`, so your original JWT will be passed, and then include a martian modifier responsible for the decoding the JWT, extracting the `sub` claim and inject it as a new header in the request to the backend.

cheers!

**Comment by Holmes89** [comment]
@kirinse we had a similar thing we wanted to do at our company and this is what we did because we need all requests going through our API gateway to be authed.

We created an `Auth` struct that houses any sort of config information we need for Authentication. That struct we added three methods:

```
func (a *Auth) authProxy(p proxy.Proxy) proxy.Proxy {
  return func(ctx context.Context, request *proxy.Request) (*proxy.Response, error) {
    ....
    // set your auth stuff here, add your headers here
   return p(ctx, request)
  }
}
```

```
func (a *Auth) errorHandler(err error) int {
   // This is where if you throw errors around authorization you should set the HTTP code
}
```
```
func (a *Auth) AuthenticatedHandler(configuration *config.EndpointConfig, proxy proxy.Proxy) gin.HandlerFunc {
	configuration.HeadersToPass = append(configuration.HeadersToPass, "Authorization")
	return krakendgin.CustomErrorEndpointHandler(configuration, a.authProxy(proxy), a.errorHandler)
}
```
I think this solution only works if you expect all endpoints to be authed.

**Comment by kpacha** [comment]
It also can be done using a LUA script. check this config snippet https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L492-L501 and  the related lua code https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/lua/collection.lua#L1-L10
