### ISSUE TITLE
Self-signed https certificates

### ISSUE THREAD

**Issue by danielfbm** [devopsfaith/krakend#251]
I am currently trying to proxy requests to our backends but in most cases they generate self-signed certificates. When accessing the services I keep getting this error: `x509: certificate signed by unknown authority`. I am aware that including the certificates in the os's accepted certs folder would solve this issue, but it would increase our workload by a lot (image lots of services in a kubernetes cluster).

I looked through the documentation and could not find any solution to this case, and investigating go's standard package I found [this PR](https://go-review.googlesource.com/c/go/+/33157/2/src/cmd/pprof/internal/fetch/fetch.go) . Looking here I see that there was a PR that did most of the work necessary https://github.com/devopsfaith/krakend/pull/134/files

It would be nice if the `InsecureSkipVerify` option would be available for configuration. 

If some guidelines are provided I am available to submit a PR

**Comment by kpacha** [comment]
Hi, @danielfbm and welcome to the KrakenD community!

I think enabling the `InsecureSkipVerify` flag for all the http clients used by the gateway will make it very hard to avoid misconfigurations and security holes. From the stdlib itself:

```
        // InsecureSkipVerify controls whether a client verifies the
        // server's certificate chain and host name.
        // If InsecureSkipVerify is true, TLS accepts any certificate
        // presented by the server and any host name in that certificate.
        // In this mode, TLS is susceptible to man-in-the-middle attacks.
        // This should be used only for testing.
```

If you don't want to add several certificates to the system ca, maybe you should use a single 'master' certificate to sign all your backend certs and just add this one to the system ca.

You can also build a custom docker container extending the official KrakenD image and add the cert to the CA there, so no extra operational work is required until you want to update your KrakenD version.

cheers
