### ISSUE TITLE
Error #01: context deadline exceeded

### ISSUE THREAD

**Issue by Lloyd-longfei** [devopsfaith/krakend#258]
When submitting a large number of data requests, prompt the above

**Comment by Lloyd-longfei** [comment]
Please give me some help.

**Comment by YucelCelik** [comment]
ne var lan gökçe?

**Comment by kpacha** [comment]
hi @Lloyd-longfei and welcome to the KrakenD community!

Please, check your global (default) timeout and the timeout of the endpoint you're consuming. More on the documentation: https://www.krakend.io/docs/throttling/timeouts/

Cheers!
