### ISSUE TITLE
Krakend gateway parameter data type mismatch error

### ISSUE THREAD

**Issue by ultrasonicsoft** [devopsfaith/krakend#259]
Hi There,

I am trying to use Krakend with .NET core 2.2 Web API. So far I am able to route simple GET, POST routes but when I am trying to route parameterised routes then I am getting type conversion issue.

krakend.json configuration part:
```
{
      "endpoint": "/route/api/method/{someId}",
      "method": "DELETE",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/api/bemethod/{someId}",
          "encoding": "json",
          "extra_config": {},
          "sd": "static",
          "host": [
            "https://localhost:5001"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
   ```
From POSTMAN, I am firing DELETE request like this:
` http://localhost:8080/route/api/method/5cf1a41b0ae9c421fb3bdcaa `

kraken output log:

```
[GIN] 2019/06/01 - 00:28:32 | 500 |  123.162448ms |             ::1 | DELETE   /route/api/method/5cf1a41b0ae9c421fb3bdcaa
Error #01: json: cannot unmarshal number into Go value of type map[string]interface {}

```

Nevertheless, backend API receive parameter correctly and does its business logic perfectly. After that, POSTMAN receive error code 500 Internal server. If I hit backend API directly, then I receive 200 status code.

Could you please let me know what could be issue here?

Thanks

**Comment by alombarte** [comment]
Hi @ultrasonicsoft,

When you configure an endpoint that uses a backend with json encoding, KrakenD expects to find a json object in the backend response (e.g: ´{ "success": true}`) that then is forwarded the user. You still have the chance of manipulating the response.

The error in the log is telling you that KrakenD is unable to recognize a valid JSON output in the backend response. Make sure that you are returning a valid JSON object. If you don't need to manipulate this response you can just forward the user query to the backend with the no-op encoding.

```
{
      "endpoint": "/route/api/method/{someId}",
      "method": "DELETE",
      "output_encoding": "no-op"
      "backend": [
        {
          "url_pattern": "/api/bemethod/{someId}",
          "encoding": "no-op",
          "host": [
            "https://localhost:5001"
          ]
        }
      ]
    }
```
Please also note that I removed unnecessary fields, See the [houskeeping article](https://www.krakend.io/blog/housekeeping-configuration-file/).

Let me know if this worked for you.

**Comment by ultrasonicsoft** [comment]
Hi @alombarte,

Thank you for your quick response and housekeeping article link.

Your solution did fix the issues for DELETE and PUT requests but for POST request I am still getting 500 error code.

Here is my POST endpoint .Net Core code.

```
        [HttpPost]
        public IActionResult Create([FromBody]RecommendationModel recommendation)
        {
            _recommendationsService.Create(recommendation);

            //return Ok(recommendation);
            return CreatedAtRoute("GetRecommendation", new { id = recommendation.Id.ToString() }, recommendation);
        }

```

Note that [CreatedAtRoute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.createdatrouteresult?view=aspnetcore-2.2) returns a 201 response with a Location header. 

Here is Krakend console output:
```
[GIN] 2019/06/01 - 23:19:35 | 500 |  308.322193ms |             ::1 | POST     /exchange/nse/recommendations
Error #01: Invalid status code
``` 

Another point, if I use `Ok(recommendation)` which returns 200 response then everything is good. But I would like to return the location header for POST response for standard sake.

Could you please let me know how to resolve this?

Thanks and Regards,
Balram Chavan

**Comment by alombarte** [comment]
Hi Balram,

It's the same issue you've been facing already, KrakenD considers that there's nothing to manipulate when the backend is responding with a `201`. I would use the `no-op` again in this case. In general terms, it looks like your ecosystem will work better with `no-op` encoding for non-`GET` requests.

**Comment by ultrasonicsoft** [comment]
Hi @alombarte,

Thanks for quick response. CreatedAtRoute() does sends json response so 'no-op' wouldn't work. Nevertheless, I found issue was in my backend as I was sending incorrect GET endpoint for location header. Fixed it and all CRUD api endpoints are being served by Krakend gateway. 

Thanks again!

Regards,
Balram
