### ISSUE TITLE
jwt validator not working if no-op is used

### ISSUE THREAD

**Issue by ybillwang** [devopsfaith/krakend#260]
I'm trying to configure my endpoint as no-op while keeping the jwt validation. From the official document it says 

> On the other hand, the router pipe’s features (from client to KrakenD) remain unaltered, meaning that for instance you can still rate-limit your end-users or require JWT authorization to name a few examples.

But it seems that when no-op is used, the jwt validator is no longer working (seems ignored). 
Below is my json config
```json
{
  "version": 2,
  "timeout": "180s",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "api gw",
  "extra_config": {
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [ "*" ],
      "allow_methods": [ "POST", "GET", "DELETE", "OPTIONS", "PATCH", "PUT" ],
      "allow_headers": [ "Authorization", "Content-Type" ]
    }
  },
  "endpoints": [
    {
      "endpoint": "/aaa/authorize/",
      "output_encoding": "no-op",
      "method": "GET",
      "headers_to_pass": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "/aaa/authorize/",
          "host": [
            "http://aaa:9001"
          ],
          "encoding": "no-op"
        }
      ],
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
            "alg": "RS256",
            "jwk-url": "http://aaa:9001/aaa/jwk/"
        }
      }
    }
  ]
}
```
When no-op is enabled as shown in the json config and request is sent with invalid token, it is supposed to return 500 and no content, but instead it actually returns 200 and the restricted content. The response headers are
>Content-Length →103
Content-Type →application/json
Date →Tue, 11 Jun 2019 07:28:11 GMT
Server →gunicorn/19.9.0
X-Frame-Options →SAMEORIGIN
X-Krakend →Version 0.9.0
X-Krakend-Completed →false

When no-op is removed from the configuration and request is sent with invalid jwt token, it behaves as expected. The response headers are
>X-Krakend →Version 0.9.0
X-Krakend-Completed →false
Date →Tue, 11 Jun 2019 07:20:47 GMT
Content-Length →0

**Comment by kpacha** [comment]
hi @ybillwang and welcome to the KrakenD community!

I tried using `no-op` encoding with the [playground](https://github.com/devopsfaith/krakend-playground) and it worked. Also, notice that the mw should return a 401 when the request is rejected.

```
$ curl -iH'Authorization: bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNpbTIifQ.eyJhdWQiOiJodHRwOi8vYXBpLmV4YW1wbGUuY29tIiwiZXhwIjoxNzM1Njg5NjAwLCJpc3MiOiJodHRwczovL2tyYWtlbmQuaW8iLCJqdGkiOiJtbmIyM3Zjc3J0NzU2eXVpb21uYnZjeDk4ZXJ0eXVpb3AiLCJyb2xlcyI6WyJyb2xlX2EiLCJyb2xlX2IiXSwic3ViIjoiMTIzNDU2Nzg5MHF3ZXJ0eXVpbyJ9.htgbhantGcv6zrN1i43Rl58q1sokh3lzuFgzfenI0Rk' http://192.168.99.100:8080/private/custom
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 435
Content-Type: application/json
Date: Tue, 11 Jun 2019 11:58:18 GMT
Expires: Fri, 19 Jul 2019 11:58:18 GMT
Last-Modified: Tue, 04 Apr 2017 20:38:05 GMT
Server: lwan
X-Krakend: Version 0.9.0
X-Krakend-Completed: false

{
	"id_user": 1,
    "firstName": "John",
    "lastName": "Smith",
    "age": 25,
    "address":
    {
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": "10021"
    },
    "phoneNumber":
    [
        {
            "type": "home",
            "number": "212 555-1234"
        },
        {
            "type": "fax",
            "number": "646 555-4567"
        }
    ]
}
```
send the token without the last char and you'll get the 401
```
$ curl -iH'Authorization: bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNpbTIifQ.eyJhdWQiOiJodHRwOi8vYXBpLmV4YW1wbGUuY29tIiwiZXhwIjoxNzM1Njg5NjAwLCJpc3MiOiJodHRwczovL2tyYWtlbmQuaW8iLCJqdGkiOiJtbmIyM3Zjc3J0NzU2eXVpb21uYnZjeDk4ZXJ0eXVpb3AiLCJyb2xlcyI6WyJyb2xlX2EiLCJyb2xlX2IiXSwic3ViIjoiMTIzNDU2Nzg5MHF3ZXJ0eXVpbyJ9.htgbhantGcv6zrN1i43Rl58q1sokh3lzuFgzfenI0R' http://192.168.99.100:8080/private/custom
HTTP/1.1 401 Unauthorized
Date: Tue, 11 Jun 2019 11:58:33 GMT
Content-Length: 0
```
I'd check your backends, looking for the missing header

**Comment by ybillwang** [comment]
@kpacha Thanks for the prompt response. I've got a few questions related to your reply.
1. `I'd check your backends, looking for the missing header`
Could provide me some clue about what missing headers should I look for?

2. `send the token without the last char and you'll get the 401`
But in the doc's faq section, it says "By default, the gateway will always send an HTTP status 500 if the backend returns any status above 400."

**Comment by kpacha** [comment]
maybe that's the thing I was missing here... are your backends trying to check the JWT? it's a job for the gateway. If the gateway accepts a token (it does not return a 401), the backends should not reject it

regarding the "backend inspection", I'd suggest you to start by checking the logs. Maybe your backends will tell you there what's going on.

cheers!

**Comment by ybillwang** [comment]
> maybe that's the thing I was missing here... are your backends trying to check the JWT? it's a job for the gateway. If the gateway accepts a token (it does not return a 401), the backends should not reject it
> 
> regarding the "backend inspection", I'd suggest you to start by checking the logs. Maybe your backends will tell you there what's going on.
> 
> cheers!

Thanks. I'll look into my backend and get back to you tomorrow.

**Comment by ybillwang** [comment]
Hi @kpacha , by comparing things between playground files and that of mine, I got the problem solved by fixing the following two things.
1. Add `"disable_jwk_security": true` in the validator settings, because my jwk-url is http
2. Fix the json response of my jwk-url. Previously, it only returns one jwk as a single json object, which is not valid. The correct one should be something similar as the public.json in the playground.

As it is purely my problem, I will close the issue now. Thanks again for your help.
