### ISSUE TITLE
Add support for expr

### ISSUE THREAD

**Issue by antonmedv** [devopsfaith/krakend#261]
Please, add support for expressions via [expr](https://github.com/antonmedv/expr) evaluator.

**Comment by alombarte** [comment]
Hi @antonmedv,

Could you explain what is the rationale behind this request besides being your personal project? We already support expressions with CEL https://www.krakend.io/docs/endpoints/common-expression-language-cel/

**Comment by antonmedv** [comment]
Hi, didn’t know what this feature existed. I don’t suggest to change cel to expr, but expr is faster btw. I was thinking what if you don’t have this feature yet, it maybe possible to add it using my project (yes, I’m looking for big users because I’m interested in it). 

But anyway, if you have any other projects, please, consider my project. I'll be very thankful. 

Thanks.

**Comment by alombarte** [comment]
Thanks, I was assuming you were suggesting a simple swap, and I was expecting at least some reasoning behind it.

KrakenD is evolving all the time and looking to be a better product. Have no doubt that if we find a better tool to solve a problem we will thorughly review it.

We are open to listen, so if you still want to explain us the benefits of supporting expr vs CEL, nothing is written in stone. What I can tell you that CEL is already adopted and being used so supporting both systems has to be well justified.

Thanks

**Comment by antonmedv** [comment]
Basically, CEL is implemented by traversing AST tree, and **expr** is using own bytecode machine which gives a speed boost. CEL has a concept of partial state, and expr last it. CEL required to define everything be own DSL, expr uses reflection on compile time and allows to use any go structs, methods, etc.
But if feature already implemented I think there is no reason to rewrite it anyway 🙂
