### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by saulfrank** [devopsfaith/krakend#262]
It would be amazing to integrate Swagger UI with Kraken D. This helps the rest of the team see the apis in a user friendly format and helps with documentation.

**Comment by alombarte** [comment]
Hi @saulfrank ,

Swagger is already integrated but it's only available to Enterprise subscribers:
![Studio](https://i.ibb.co/VpnxLnB/Captura-de-Pantalla-2019-06-20-a-les-16-05-26.png)

**Comment by saulfrank** [comment]
That is a shame.

**Comment by alombarte** [comment]
Just a clarification: The Enterprise is not a version that replaces KrakenD-CE. Under the Enterprise subscription, we have a tool named KrakenD Studio that helps developers to do more stuff.

To generate swagger documentation you need to inspect all the traffic coming from the backends, so you can create the map of responses delivered by the backends. This is something you don't want to do in production as it is an intensive and consuming operation, and this is why it needs to be separated.

**Comment by saulfrank** [comment]
OK thanks, that makes sense.
