### ISSUE TITLE
Filter backend's response by value

### ISSUE THREAD

**Issue by joanlopez** [devopsfaith/krakend#267]
Hello guys,

I've started to play with KrakenD to check if it satisfies some of the requirements I have for a given project (I'm not really sure if an API gateway should do it).

One of the first questions that came to my mind was:

- Is there any way to filter / find inside the backend's response?

Let's guess we want to expose an endpoint like: `/products/{productID}` but our backend only have the endpoint `/products`, so I would need to be able to filter the backend's response by value (id == productID, or something like that).

How can it be achieved?
I've seen there are some ways to do array manipulations but I cannot find a way (i.e. JSONPath or similar) that allows me this kind of search.

In addition, could this parameter be taken from the query params? 
I cannot find in the whole documentation a way to use the query params as variables, as the ones taken directly from the URL.

Sorry if I've misunderstood something, but I'm looking for this kind of features precisely because I see the tool as a very good choice for my project.

Thank you so much!

**Comment by kpacha** [comment]
This kind of data manipulation can be done with a post execution lua script. Check the integration test:

https://github.com/devopsfaith/krakend-ce/blob/0.10-dev/tests/fixtures/krakend.json#L440-L474

https://github.com/devopsfaith/krakend-ce/blob/0.10-dev/tests/fixtures/specs/lua_1.json

Lua scripts can access requests and responses as shown at https://github.com/devopsfaith/krakend-lua/blob/master/proxy/proxy_test.go#L77-L104

The lua module will be released with the 0.10 version but you can already try it using the docker image `devopsfaith/krakend:0.10.0-dev`
