### ISSUE TITLE
OAuth 2.0 Token Introspection

### ISSUE THREAD

**Issue by tagkiller** [devopsfaith/krakend#270]
Hi all,

I have a question, is there any way to achieve **OAuth 2.0 Token Intropsection (RFC-7662)** using KrakenD or via an extension ?

Thanks in advance for your help !

**Comment by kpacha** [comment]
hi, @tagkiller and welcome to the KrakenD community.

It's possible to achieve the same features described in the RFC-7662 without calls to external services. Just go with JWT and bloomfilters.

signed JWT will give you the meta-information and the state can be verified with the JWT itself and the bloomfilter.

check the playground for a running example:
![playground](https://github.com/devopsfaith/krakend-playground/raw/master/composer-env.png?raw=true)

https://github.com/devopsfaith/krakend-playground

**Comment by tagkiller** [comment]
Thanks a lot for your quick answer, I couldn't expect a better answer :-)

I'm closing the issue.

**Comment by abbluiz** [comment]
What if my OAuth 2.0 implementation/server does not support self-validating JWT tokens?

**Comment by kpacha** [comment]
then, you'll need a custom handler plugin intercepting the requests and asking your identity provider for the details of the token
