### ISSUE TITLE
[Question] - How to fetch multiple API in songle endpoint ?

### ISSUE THREAD

**Issue by FerdinaKusumah** [devopsfaith/krakend#272]
Example: 
[GET] [/authors] -> [backend_url -> http://localhost:8000/authors] return all authors
[GET] [/books] -> [backend_url -> http://localhost:8000/books] return all books
How to create single end point that return authors and books in one request.
[GET] [/author-books] ->  [backend_url ->[ http://localhost:8000/books,  http://localhost:8000/authors]] return all authors and books

Thank you

**Comment by taik0** [comment]
Hi @FerdinaKusumah and welcome to the KrakenD community!

Please, check this documentation [link](https://www.krakend.io/docs/backends/overview/#simple-example).
If you want more complex examples, please check the [playground](https://github.com/devopsfaith/krakend-playground) or the [integration tests krakend-ce](https://github.com/devopsfaith/krakend-ce/tree/master/tests/fixtures).

Cheers!

**Comment by FerdinaKusumah** [comment]
You rock .. :fire: :fire: :fire:
Thank you :clap: :clap: @taik0
