### ISSUE TITLE
Add api key authentication mechanism for clients

### ISSUE THREAD

**Issue by umarhussain15** [devopsfaith/krakend#274]
I read the documentation of the krakend and I'm unable to find a solution which allow me to setup krakend to generate api keys which I can distribute to clients and put access control on krakend proxy.

Will krakend get this feature by default? Kong has this feature but I like the speed of krakend. So having apuiKey auth for clients will be a good feature.

**Comment by alombarte** [comment]
Hi @umarhussain15 

Generation of keys for external access is not a generic feature that KrakenD offers under open source, there are small things you could do to achieve this functionality if you have a controlled set of users. This functionality would require [Enterprise](https://www.krakend.io/enterprise/), write to us to know more.

**Comment by packeteer** [comment]
so is this available in Enterprise version?

**Comment by abhisekp** [comment]
Can this be implemented in the open source version using plugin?
