### ISSUE TITLE
is endpoints match support prefix matching?

### ISSUE THREAD

**Issue by ocoderr** [devopsfaith/krakend#275]
Example:
a  backend A have there endpoint
[backend_url -> http://backend-a/api/a]
[backend_url -> http://backend-a/api/b]
[backend_url -> http://backend-a/api/c]

can i set a endpoint like this
[/backend-a/*] --->http://backend-a/api/*

can route all match request to backend-a?
Thank you

**Comment by kpacha** [comment]
`/backend-a/{endpoint}` ---> `http://backend-a/api/{endpoint}`
But it works just with a single level (`/backend-a/foo/bar`  will not match)

**Comment by ocoderr** [comment]
thanks @kpacha 
Is there a plan to support prefix matching？

**Comment by kpacha** [comment]
no, there is not because we think that's out of the scope of an api gateway. pure http routing can be done with almost any LB.

we wrote some time ago about the topic: https://www.krakend.io/blog/what-is-an-api-gateway/
