### ISSUE TITLE
Which JTI to use for JWT token revocation?

### ISSUE THREAD

**Issue by nocquidant** [devopsfaith/krakend#276]
Hi, 

I am currently playing with krakend (which I find very nice) and jwt revocation but I can't manage to get revocation work.

This is what i get so far (configuration file is below):

```
curl localhost:8888/private/perso
# [GIN] 2019/09/03 - 17:14:41 | 401 |      43.201µs |       127.0.0.1 | GET      /private/perso

curl localhost:8888/private/perso --header "authorization: Bearer $access_token"
# [GIN] 2019/09/03 - 17:16:05 | 200 |    1.179214ms |       127.0.0.1 | GET      /private/perso
```

So far so good. Then I add my access token for revocation (using code from your playground adapted for JSON):

```
curl -d "{\"jti\":\""$access_token"\"}" -H "Content-Type: application/json" -X POST http://localhost:8889/add
# krakend server response is "added elements: 1", so communication with grpc is OK
```

But I still can access my API using my access_token... 

```
curl localhost:8888/private/perso --header "authorization: Bearer $access_token"
# [GIN] 2019/09/03 - 17:16:05 | 200 |    1.179214ms |       127.0.0.1 | GET      /private/perso
```

So I guess the expected jti is not the entire access token... Using jwt.io I can't find an ID in my access token... Could you please tell me how to get a jti from my access_token? My access token was generated using the [Client Credential Flow](https://auth0.com/docs/flows/guides/client-credentials/call-api-client-credentials) from auth0.

Thanks,
-nick

My configuration is below.

```
{
   "version": 2,
   "name": "Dummy API Gateway",
   "port": 8888,
   "cache_ttl": "3600s",
   "timeout": "3s",
   "extra_config": {
      "github_com/devopsfaith/krakend-gologging": {
         "level": "DEBUG",
         "prefix": "[KRAKEND]",
         "syslog": false,
         "stdout": true
      },
      "github_com/devopsfaith/krakend-metrics": {
         "listen_address": ":8090"
      },
      "github_com/devopsfaith/bloomfilter": {
        "N": 10000000,
        "P": 0.0000001,
        "HashName": "optimal",
        "TTL": 1500,
        "port": 1234,
        "TokenKeys": ["jti"]
      }
   },
   "endpoints": [
      {
         "endpoint": "/v1/health",
         "backend": [
            {
               "url_pattern": "/health",
               "sd": "dns",
               "host": [
                  "greeting.service.consul"
               ],
               "disable_host_sanitize": true
            }
         ]
      }, {
         "endpoint": "/private/perso",
         "backend": [
            {
               "url_pattern": "/custom?name=Nicolas",
               "sd": "dns",
               "host": [
                  "greeting.service.consul"
               ],
               "disable_host_sanitize": true
            }
         ],
         "extra_config": {
            "github.com/devopsfaith/krakend-jose/validator": {
               "alg": "RS256",
               "cache": true,
               "audience": [
                  "http://greeting.service.local"
               ],
               "jwk-url": "https://dev-dfn-g7fc.eu.auth0.com/.well-known/jwks.json"
            }
         }
      }
   ]
}
```

**Comment by kpacha** [comment]
hi @nocquidant 

I think the issue here is because you're sending the entire JWT instead of its `jti` claim. At the playground, we use auth0 and a custom dummy generator and both include the `jti` claim.

Anyway, if your JWT don't have a `jti` claim, you can use any other unique claim, like `sub`. Just remember to add the selected claim to the `"TokenKeys"` list

**Comment by nocquidant** [comment]
Oups, I totally missed the "TokenKeys" list :)
Thank you
--nick

**Comment by DucVuMinh** [comment]
@nocquidant I'm learning config krakend with bloom filter, I saw your issue have service http://localhost:8889/add to add TokenKeys to bloomfilter, but I don't know how you config this service.
Can you help me with that ?

**Comment by kpacha** [comment]
@DucVuMinh you'll find a working example at the playground: https://github.com/devopsfaith/krakend-playground/tree/master/jwt-revoker

**Comment by DucVuMinh** [comment]
@kpacha thank you for responding, I'm following this example

**Comment by geetha77m** [comment]
@nocquidant I'm playing around with config krakend with bloom filter, I saw your issue having service http://localhost:8889/add to add TokenKeys to bloomfilter, but I don't know how you config this service.
It would be helpful if you can help with more information on it.

**Comment by unduu** [comment]
@kpacha iam trying to revoke http://localhost:9000/add/?jti=mnb23vcsrt756yuiomnbvcx98ertyuiop
but still can access /private/custom
