### ISSUE TITLE
Support to kafka

### ISSUE THREAD

**Issue by Otoru** [devopsfaith/krakend#281]
**Is your feature request related to a problem? Please describe.**
No, krakend works very well for me.

**Describe the solution you'd like**
The idea is very similar to what is already implemented for RabbitMQ, but allowing integration with Apache Kafka.

**Describe alternatives you've considered**
I am not currently using krakend on projects where kafka is a prerequisite :(

**Additional context**
N/A

**Comment by alombarte** [comment]
Thank you very much for your suggestion @Otoru. Definitely, this is something we have considered sometime in the past and will be on the table once again.

Don't expect a quick resolution on this issue but we will keep you updated when there is news.

In the meantime, I would love to hear those use cases where Kafka is not a prerequisite and you are using KrakenD. If you want to keep it private you can write me at albert AT krakend.io.

Thank you very much for bringing this in.

**Comment by Otoru** [comment]
I am developing a project with friends where we want to make a system for event management.

As a personal project of ours, we opted for a microservice architecture to study this pattern and krakend has been a wonderful way of exposing our endpoints to the outside world (but communication between them is done with kafka).

In some personal projects where I have endpoints that need to be exposed on the network, I'm using krakend to expose them and do rate-limiting control.

**Comment by Otoru** [comment]
A question not linked to this point, in situations like this (kafka support) or in cases I have seen in other issues (status code translation for example).

If someone contributes code, is it recommended to keep a fork or is krakend open to community PRs?

**Comment by kpacha** [comment]
in all the projects managed by devopsfaith, Issues, questions and PR are very welcome. 

I think the support for kafka should be in a dedicated module (https://github.com/devopsfaith/krakend-contrib#transports).

**Comment by Otoru** [comment]
I agree with the separate module for kafka. It would keep everything more organized if it were actually developed.

I'm going back to studying golang so I can contribute to the project someday.

**Comment by alombarte** [comment]
Kafka support was released last February: https://www.krakend.io/blog/krakend-1.1-release-notes/

We can close this issue
