### ISSUE TITLE
Support for krakend on gcp and azure platforms 

### ISSUE THREAD

**Issue by boazlautman** [devopsfaith/krakend#282]
Same like you have for the AWS

**Comment by alombarte** [comment]
Hi @boazlautman,

KrakenD can run on AWS but also on GCP and Azure. What do you have in mind? I am maybe lacking a bit of context.

Thanks

**Comment by alombarte** [comment]
Are you referring to the KrakenD image in the [AWS marketplace](https://aws.amazon.com/marketplace/pp/B07KXM7BRG)? This is a Linux with KrakenD pre-installed

There are more options to deploy KrakenD. If you are a user of GCP or Azure and don't want to install a Linux box the recommended solution is to run Docker containers. We have a prebuilt Docker container with krakend, you only need to set your own `krakend.json` configuration and start it in Kubernetes or similar service. For instance, in Azure you can run our container in [AKS or Container Instances](https://azure.microsoft.com/en-us/product-categories/containers/), and the same thing happens [with Google](https://cloud.google.com/container-options/)

To run our docker container you need to [generate a krakend.json](http://designer.krakend.io) file with your configuration and then run it with:
```
docker pull devopsfaith/krakend
docker run -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend run --config /etc/krakend/krakend.json
```
You can test these two lines in your computer and you will have KrakenD running on port 8080.

**Comment by boazlautman** [comment]
Thanks.
I will check the docker option.
Keep your good job!
Your gateway rocks!
