### ISSUE TITLE
Panic while registering different routes

### ISSUE THREAD

**Issue by pardhasm** [devopsfaith/krakend#292]
Krakend check is not giving any errors. But on running, panic is displaying the following message.

`panic: 'report' in new path '/system/get/report/data/:ID' conflicts with existing wildcard ':APPLICATION_ID' in existing prefix '/system/get/:ID'`

Both the endpoints are different and there are many similar endpoints in the service I am using (Legacy, cannot change).

How can these be resolved into separate paths?

My config:

```
{
  "version": 2,
  "extra_config": {},
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "Test",
  "port": 8081,
  "endpoints": [
    {
      "endpoint": "/system/get/report/data/:ID",
      "method": "GET",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/system/get/report/data/:ID",
          "encoding": "json",
          "sd": "custom",
          "extra_config": {},
          "host": [
            "http://127.0.0.1:8080"
          ],
          "disable_host_sanitize": true
        }
      ]
    },
{
      "endpoint": "/system/get/:ID",
      "method": "GET",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/system/get/:ID",
          "encoding": "json",
          "sd": "custom",
          "extra_config": {},
          "host": [
            "http://127.0.0.1:8080"
          ],
          "disable_host_sanitize": true
        }
      ]
    }
  ]
}
```

Similarly 
`panic: wildcard route ':BRAND' conflicts with existing children in path '/v2/vehicle/orp/:BRAND/:MODEL/:CITY'`

**Comment by kpacha** [comment]
Since you're creating a new API, you can use endpoint patterns different that the patterns exposed by the consumed backends

For more on the issue: https://github.com/devopsfaith/krakend-ce/issues/136

**Comment by pardhasm** [comment]
@kpacha I'm able to find mux replacements except for bot detector. Should I just remove it or use gin as is?

**Comment by kpacha** [comment]
Currently, the botdetector package supports just the gin router. You should go without it or extend it adding support for mux.

Regarding your code, I'm afraid it will require some more work than just replacing the package name. The interfaces of both packages are quite different. (notice that the snippet at the linked issue doesn't define middlewares nor engine properties)

**Comment by pardhasm** [comment]
@kpacha  I was able to modify the code and use gorilla mux. It is running properly for static routes.
For parameterised routes, URI parser is converting routes like 
`/employee/{id} -> /employee/:id`
this is resulting in invalid regex.
Gorilla router expects endpoints to be of the form` /employee/{id}`. 

> / Path adds a matcher for the URL path.
> // It accepts a template with zero or more URL variables enclosed by {}. The
> // template must start with a "/".
> // Variables can define an optional regexp pattern to be matched:
> //
> // - {name} matches anything until the next slash.
> //
> // - {name:pattern} matches the given regexp pattern.
> //
> // For example:
> //
> //     r := mux.NewRouter()
> //     r.Path("/products/").Handler(ProductsHandler)
taken from mux/route.go.

How can I skip the conversion of URLs?

**Comment by kpacha** [comment]
you can change the `config.RoutingPattern` var default value (https://github.com/devopsfaith/krakend/blob/master/config/config.go#L33) to `config.BracketsRouterPatternBuilder` (https://github.com/devopsfaith/krakend/blob/master/config/config.go#L20)

**Comment by L3tum** [comment]
@pardhasm Did you get krakend to work with Mux? I only find half-answers online and I currently have the same problem that wildcards aren't matched at all. I already changed the RoutingPattern though.
