### ISSUE TITLE
Wrong response when using shadowing

### ISSUE THREAD

**Issue by dmitriifilonenko** [devopsfaith/krakend#295]
**Describe the bug**
When I use traffic shadowing 'main' backend returns 200 when it's supposed to return 400

**To Reproduce**
Configuration used
Initially I have such configuration:

"endpoints": [
    {
      "endpoint": "/api/v1/bots/{tail}",
      "headers_to_pass": [ "*" ],
      "method": "GET",
      "extra_config": {},
      "output_encoding": "no-op",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/api/v1.0/bots/{tail}",
          "encoding": "no-op",
          "host": [            
            "x.x.x.x:5000"
          ]
        }
      ]
    }
  ]
It worked correctly, including error statuses like 400 or 401.

Then I added a shadowing:

"endpoints": [
    {
      "endpoint": "/api/v1/bots/{tail}",
      "headers_to_pass": [ "*" ],
      "method": "GET",
      "extra_config": {},
      "concurrent_calls": 1,
      "backend": [
        {
          "host": [ "x.x.x.x:5000" ],
		  "url_pattern": "/api/v1.0/bots/{tail}",
		  "encoding": "no-op"          
        },
		{
            "host": [ "y.y.y.y:5000" ],
            "url_pattern": "/api/v1.0/bots/{tail}",
            "encoding": "json",
            "extra_config": {
                "github.com/devopsfaith/krakend/proxy": {
                    "shadow": true
                }
            }
        }
      ]
    }
  ]

**Expected behavior**
In logs of my applications running on the given two hosts I see that request come and each of applications handles it correctly. 
But eventual response from API gateway is wrong. When for example I expect 400, I see 200 instead and {} in the response's body.

I guess that it might be my fault somewhere in configuration since I'm new to KrakenD. But then what am I doing wrong?

**Comment by kpacha** [comment]
you can not mix `no-op` pipes with data manipulation functionalities. If you want to use the shadow module, use other decoder (`json`, `xml`, etc).

**Comment by dmitriifilonenko** [comment]
Hi Daniel! Thanks a lot for the feedback!

I have realized this myself when looked into source code. :-)

However it looks like an unnecessary restriction in this specific use-case because you still have an only one 'supplier' (main backend) of responses and statuses of requests, another one (shadow backend) is just a silent consumer.

Basically traffic-shadowing was the main feature (in addition to routing of course) which made me interested in KrakenD. I'm working on extraction of a specific functionality from an (monolith) application running on Ruby-on-rails to a separate (micro)service running on .NET Core. This is quite a big change and I need a way to test if this functionality will work the same way as now.
So I wanted to shadow a traffic to the new service without any impact on the currently running one. This means that I want an API gateway to return data and **request statuses** from the main backend without any changes and to let traffic into the shadow backend without letting a response to get out.
Changing decoder to json in my use-case makes KrakenD to change statuses of responses, like 401 -> 500. Which infers a breaking impact on the main backend functionality.
