### ISSUE TITLE
Build plugin

### ISSUE THREAD

**Issue by phamvinhdat** [devopsfaith/krakend#301]
when I build plugin, i get warning `plugin was built with a different version of package sync/atomic`
Please show me how to fix it, thanks:
WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0  plugin was built with a different version of package sync/atomic

**Comment by oskoi** [comment]
Hi!
@phamvinhdat try to use the same version of golang as krakend (including patch part).
One of the problems of golang plugin is the need to use the same version of dependencies as the host (in your case host is krakend)

**Comment by kpacha** [comment]
@phamvinhdat the 1.0.0 was built with go 1.13

as @oskoi commented, in order to use plugins with the official release, you should compile them with the same version of the stdlib and any shared libs

**Comment by phamvinhdat** [comment]
thanks
