### ISSUE TITLE
Retriable Load Balancer

### ISSUE THREAD

**Issue by oskoi** [devopsfaith/krakend#302]
**Is your feature request related to a problem? Please describe.**
If use default round robin load balancer and one of the requests fails (refused connection or received 5xx), then there is no way to automatically retry it to another host.

**Describe the solution you'd like**
It would be nice to add feature to load balancer with retry policy (strategy, number of retries, etc)

**Comment by kpacha** [comment]
@oskoi that's a design choice. Health-checking the backends is one of the goals of service discovery systems (like consul, etcd, eureka, ...) or even container/instance management platforms (k8s, mesos, ...). You can use the available krakend components to integrate your gateway with them (some using their own client, some using DNS SRV records). https://www.krakend.io/docs/service-discovery/overview/

there is also a circuit breaker available to avoid smashing already failing backends, but it is independent (orthogonal) of the LB layer. https://www.krakend.io/docs/backends/circuit-breaker/

on the other hand, we designed the KrakenD with scalability and resiliency as a key principles. By our experience, in distributed environments failing fast and ensuring graceful degradation is better than retrying (due the increase of resource consumption, the queue backup effect and so on) https://www.krakend.io/docs/extending/the-big-picture/#the-krakend-rules

**Comment by nicodeg87** [comment]
Hi guys, sorry for reviving this old thread. I have a question regarding this feature request.

How does krakend behaves in case of DNS SRV service discovery when one of the nodes of the backend is not available? (Asking due that documentation mentions a 30 seconds cache of dns results, it means that during deployment/failure on some of the nodes krakend will get errors)

ideally if dns srv service has 10 nodes, and one of them fails for instance at connection level, it should not return this error to clients and should use one of the other nine available.

thanks!

**Comment by alombarte** [comment]
The DNS can be configured in Lura with `dnssrv.TTL = XX` setting the number of seconds you want that cached. 
The option of using an external load balancer is my preferred though.
