### ISSUE TITLE
Return response headers to client

### ISSUE THREAD

**Issue by leehomewl** [devopsfaith/krakend#311]
HI:
I need help, thanks！
1   I want to output the response header of the backend feedback to the client. Is there any parameter that can be configured?  I haven't seen it for a long time.
2  Transform headers ，  Seems to have no effect, the client does not see the response header。
"endpoint": "/foo",
"extra_config": {
    "github.com/devopsfaith/krakend-martian": {
        "header.Modifier": {
          "scope": ["request", "response"],
          "name": "X-Martian",
          "value": "true"
        }
    }
}

**Comment by kpacha** [comment]
@leehomewl 

1: the only way to pass the headers from the backend response to the client is by using the `no-op` pipe: https://www.krakend.io/docs/endpoints/no-op/. Please, notice it has some limitations

2: the martian modifiers work over the request/response between the gateway and the backends, so your client will see `X-Martian` header only if it's connected to a `no-op` pipe
