### ISSUE TITLE
Response merging cannot be realized through Kraken-ce

### ISSUE THREAD

**Issue by granty1** [devopsfaith/krakend#322]
**Response merging cannot be realized through Kraken-ce**
I referred to the documentation, but after configuring the two back ends, I did not merge the responses of the two requests.

**To Reproduce**
1. Configuration used
```
{
  "version": 2,
  "extra_config": {},
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "endpoints": [
    {
      "endpoint": "/roles_pages",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/roles",
          "encoding": "json",
          "host": [
            "127.0.0.1:8001"
          ]
        },
        {
          "url_pattern": "/pages",
          "host": [
            "127.0.0.1:8002"
          ]
        }
      ]
    }
  ]
}
```
2. I started krakend-ce and went to visit the interface `/roles_pages`, but only the response of one of the requests came back, But the logs of the two back ends show that both interfaces have been called.

**Expected behavior**
Return the response combination of two interfaces.

**Logs**
[GIN] 2020/02/04 - 16:52:40 | 200 |    2.998917ms |       127.0.0.1 | GET      /roles_pages

**Additional context**
none.

**Comment by alombarte** [comment]
Hi @granty1,

If KrakenD is waiting for the backends to respond and the timeout is reached, or there is an unexpected format in the backend response, the response will be incomplete and missing any data that couldn't be fetched before the timeout happened. On the other hand, all the parts that could effectively be retrieved before the timeout happened they will do appear in the response.

At all times, the `x-krakend-completed` header returned by KrakenD contains a boolean telling you if all backends returned its content (x-krakend-completed: true) or a partial response (x-krakend-completed: false).

Could you show the output of manually calling the failing backend?:
```
curl -iG http://127.0.0.1:8001/pages
```

**Comment by granty1** [comment]
`/roles` response :
```
{
    "data": [
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "roleId": "1",
            "roleName": "Test"
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "roleId": "2",
            "roleName": "Train"
        }
    ]
}
```
`/pages` response
```
{
    "data": [
        {
            "Name": "Krakend",
            "Url": "https://krakend.io",
            "Title": "krakend page"
        },
        {
            "Name": "Grant",
            "Url": "grant.io",
            "Title": "grant page"
        }
    ]
}
```

but `/roles_pages` response:
```
{
    "data": [
        {
            "Name": "Krakend",
            "Url": "https://krakend.io",
            "Title": "krakend page"
        },
        {
            "Name": "Grant",
            "Url": "grant.io",
            "Title": "grant page"
        }
    ]
}
```

headers: `X-Krakend-Completed: true`

**Comment by granty1** [comment]
Sorry, I found that the response structure of the two back ends is the same, so one will be overwritten

**Comment by alombarte** [comment]
Consider adding in the backends:
```
"mapping": {
        "data": "pages"
      }
```
and 
```
"mapping": {
        "data": "roles"
      }
```

**Comment by granty1** [comment]
> Consider adding in the backends:
> 
> ```
> "mapping": {
>         "data": "pages"
>       }
> ```
> 
> and
> 
> ```
> "mapping": {
>         "data": "roles"
>       }
> ```

Well, thank you very much.
