### ISSUE TITLE
Some problem integrating with influxdb by metrics

### ISSUE THREAD

**Issue by granty1** [devopsfaith/krakend#324]
**Describe the bug**
I plan to send the data collected by Kraken-CE's metrics to influxdb, and display the data through the official Chronograf(data visualization) provided by influxdb

**To Reproduce**
1. Configuration used
```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[MELODY]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    },
    "github_com/devopsfaith/krakend-metrics": {
      "collection_time": "60s",
      "proxy_disabled": false,
      "router_disabled": false,
      "backend_disabled": false,
      "endpoint_disabled": false,
      "listen_address": ":8090"
    },
    "github_com/devopsfaith/krakend-opencensus": {
      "exporters": {
        "influxdb": {
            "address": "http://127.0.0.1:8086",
            "db": "melody",
            "timeout": "1s"
        }
      }
    }
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "name": "Test",
  "endpoints": [
    {
      "endpoint": "/person/{id}/{name}",
      "method": "GET",
      "extra_config": {},
      "concurrent_calls": 1,
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/person/{id}/{name}",
          "sd": "static",
          "extra_config": {},
          "method": "GET",
          "host": [
            "127.0.0.1:8001"
          ],
          "disable_host_sanitize": false
        }
      ]
    },
    {
      "endpoint": "/roles_pages",
      "method": "GET",
      "extra_config": {},
      "concurrent_calls": 1,
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/page",
          "sd": "static",
          "extra_config": {},
          "method": "GET",
          "host": [
            "127.0.0.1:8001"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
}
```

As you can see, I've configured metrics and influxdb

2. I started influxdb and telegraf(plugin-driven server agent for collecting and reporting metrics) locally with docker

3. I called the API through Kraken, but the influxdb did not receive any data, and I listened through Charles, and found that Kraken did not call any interface of port 8086

**Expected behavior**
1. There should be an HTTP request record of Kraken calling port 8086 in Charles
2. There should be data in the influxdb

**Logs**
```
▶ DEBUG creating a new influxdb client
▶ DEBUG no config for the influxdb client. Aborting
▶ WARNING influxdb: unable to load custom config
```
I checked the source code and found that the reason for these logs is that there is no namespace like `"github_com/letgoapp/krakend-influx"`

I have a few small questions. I'd like to ask 
1. what is the role of the namespace here?
2. Is the above situation due to my configuration problem or other reasons?

**Additional context**

**Comment by kpacha** [comment]
In order to see the influxdb exporter for the opcencensus integration working, you need to setup the collection part of the module configuration (https://www.krakend.io/docs/logging-metrics-tracing/opencensus/)

on the other hand, if you are willing to use the influxdb exporter for the custom metrics module, check the examples at the component https://github.com/letgoapp/krakend-influx . as you already noticed, it uses the namespace `github_com/letgoapp/krakend-influx`

**Comment by go4sachin007** [comment]
Nothing is clearly mentioned on your answer

I am struggling  with this type issue but nothing is clearly mentioned by you people

If you cannot provide support in clear word then clearly mention that you guys only help for enterprise user

I did my best effort to solve such issue for continuous 3 weeks but in vain

Simple Question: your documentation says  

`InfluxDB is a time series database designed to handle high write and query loads.

The Opencensus exporter allows you export data to InfluxDB for monitoring metrics and events. Enabling it only requires you to add the influxdb exporter in the opencensus module.

The following configuration snippet sends data to your InfluxDB:`
https://www.krakend.io/docs/telemetry/influxdb/

But nothing is happening

Please support or simply say that buy enterprise version, we will check other solutions 

Thanks
Sachin
