### ISSUE TITLE
Custom header using Martian is not getting passed to OAuth2.0 client credential server

### ISSUE THREAD

**Issue by tj-vaneerten** [devopsfaith/krakend#325]
**Describe the bug**
I am using Google Cloud Run to host a private service, and I'm trying to host an instance of Krakend also using Cloud Run. This way, I can expose Krakend publicly, while using Google's service-to-service connection to hit my backend service. According to [this article](https://cloud.google.com/run/docs/authenticating/service-to-service), Cloud Run's service-to-service authentication is done using an OAuth token. To get this token, a request has to be made to an internal url (http://metadata/computeMetadata/v1/instance/service-accounts/default/identity) from the calling service (in this case Krakend). According to [this](https://cloud.google.com/compute/docs/storing-retrieving-metadata#querying), a special header (Metadata-Flavor: Google) has to be passed or the request for the token is denied.

I followed [this doc](https://www.krakend.io/docs/authorization/client-credentials/) on how to use the OAuth2.0 Client Credentials plugin to make this call for the token. The example provided for Auth0 seems to be exactly what I needed to do. The doc mentions 
```
The Accept header is needed when sending a request to auth0. The krakend-martian component modifies the request to the backend to do that.
```

I followed these instructions but the ```Metadata-Flavor: Google``` header is not being passed to the OAuth token endpoint. I can confirm that the martian config is working and passing the header to my backend when I remove the client credentials config. But I cannot get the header to be passed on to the token endpoint

**To Reproduce**
1. Follow instructions [here](https://www.krakend.io/docs/authorization/client-credentials/) on how to setup client credentials
```
"github.com/devopsfaith/krakend-oauth2-clientcredentials": {
    "endpoint_params": {
        "audience": ["BACKEND_SERVICE"]
    },
    "token_url": "http://metadata/computeMetadata/v1/instance/service-accounts/default/identity",
    "client_id": "YOUR-CLIENT-ID",
    "client_secret": "YOUR-CLIENT-SECRET"
}
```
2. Use martian to add the custom header needed by token endpoint
```
"github.com/devopsfaith/krakend-martian": {
   "header.Modifier": {
       "scope": ["request"],
       "name" : "Metadata-Flavor",
        "value" : "Google"
    }
}
```

**Expected behavior**
I expect the header from the martian header modifier to be passed in the request to the client credential endpoint

**Comment by kpacha** [comment]
The token issuer is managed by the golang.org/x/oauth2/clientcredentials package and I don't see a proper way to extend its internal client.

I think you need to build a custom plugin responsible for dealing with the token negotiation and injecting it to the requests to your backends

**Comment by tj-vaneerten** [comment]
Got it. Thanks for clarifying.

**Comment by Yegair** [comment]
@tj-vaneerten Did you somehow solve this issue? I am having exactly the same problem. This essentially makes deploying Krakend on Cloud Run impossible, which is a shame, because IMHO it would be a great fit.
