### ISSUE TITLE
[Question] Can you create a custom function on krakend.json?

### ISSUE THREAD

**Issue by fari-99** [devopsfaith/krakend#326]
Hello, this is only a question.
I'm using Docker to run my krakend, I bind my krakend files (settings, partials, and templates) 
to it. 

so I can run it smoothly, but I need to create a special function to generate some configuration for extra_config, etc.

I read on [Go Template](https://golang.org/pkg/text/template) documentation, you can call the function using "call", unfortunately, I don't understand it. Can someone make a simple example on krakend.json and call it using "call"? like, create an increment function.

thanks for the help.

**Comment by kpacha** [comment]
from the documentation:

> call
	Returns the result of calling the first argument, which
	must be a function, with the remaining arguments as parameters.
	Thus "call .X.Y 1 2" is, in Go notation, dot.X.Y(1, 2) where
	Y is a func-valued field, map entry, or the like.
	The first argument must be the result of an evaluation
	that yields a value of function type (as distinct from
	a predefined function such as print). The function must
	return either one or two result values, the second of which
	is of type error. If the arguments don't match the function
	or the returned error value is non-nil, execution stops.

you need to inject the func-valued field in the template context and, since the context for the template execution at the flexibleconfig module is created from the settings (json files) it is not possible.
