### ISSUE TITLE
Is there any way to set any http method for endpoint?

### ISSUE THREAD

**Issue by gl-ot** [devopsfaith/krakend#327]
I have a rest api and it's really demotivating to set for each http method own endpoint.
Can I set something like `*` wildcard or list `PUT,DELETE,PATCH` for endpoint method?

**Comment by alombarte** [comment]
If you have a single endpoint with several HTTP request methods (PUT, GET, POST, etc.) you need to declare in the configuration every request method you want in the API gateway.

Maybe you are assuming and using KrakenD is a proxy server that needs to forward everything to the same server behind, but this is not the common use case it's been designed for. You might want to have different sets of transformations, manipulations, and treatment and even backend servers for the different methods and KrakenD allows you to do that.

The configuration is something you write once, and tools like [flexible-config](https://www.krakend.io/docs/configuration/flexible-config/) can ease this "pain".
