### ISSUE TITLE
Can't add a custom header to a request

### ISSUE THREAD

**Issue by soulless-viewer** [devopsfaith/krakend#328]
### Problem

When I'm trying to add custom header to a request between KrakenD and service I get an error:
`Error #01: Line 1: attempt to call a non-function object`

My **krakend.json**:
```
"endpoints":[
		{
			"endpoint":"/api/services",
			"method":"GET",
			"headers_to_pass":[
				"*"
			],
			"querystring_params":[
				"*"
			],
			"extra_config":{
				"github.com/devopsfaith/krakend-lua/proxy":{
					"pre":"local r = request.load(); r:header('x-rh-identity', '1234'); print(r:headers('x-rh-identity'));"
				}
			},
			"output_encoding":"json",
			"concurrent_calls":1,
      "backend":[
				{
					"url_pattern":"/api/services",
          "extra_config":{},
					"host":[
						"http://<ip>:<port>"
					]
				}
			]
		}
	]
```

> This is the most simplified version of the part of my configuration that I checked when trying to find a working solution.

This example from official examples: https://www.krakend.io/docs/endpoints/lua/#examples
```
"extra_config": {
      "github.com/devopsfaith/krakend-lua/proxy": {
        "pre": "print('Lua proxy!'); local r = request.load(); r:header('X-from-lua', '1234');",
      }
}
```
---------------------
### Final goal

I want to perform this scheme:

1. Receive the request
2. Get info from jwt-token from the Cookie
3. Add custom header with this info to the request
4. Send a request further to the service

**Comment by soulless-viewer** [comment]
WTF, guys?! I spent 3 hours on it.
This example from official examples: https://www.krakend.io/docs/endpoints/lua/#examples
```
"extra_config": {
      "github.com/devopsfaith/krakend-lua/proxy": {
        "pre": "print('Lua proxy!'); local r = request.load(); r:header('X-from-lua', '1234');",
      }
}
```
And this is right example:
```
"extra_config": {
      "github.com/devopsfaith/krakend-lua/proxy": {
        "pre": "print('Lua proxy!'); local r = request.load(); r:headers('X-from-lua', '1234');",
      }
}
```
>r:header**s**('X-from-lua', '1234');

I decided that it's a specific function for setting header which I don't understand.

**Comment by alombarte** [comment]
Thanks @soulless-viewer,

I am sorry that you had to spend 3 hours to find a missing "S" in the documentation, believe me, that was not on purpose Thanks for your WTF, you made my day.

If this gives you any comfort, we spent 4 years developing a 100% open source product that you can use today.

Have a nice day

**Comment by soulless-viewer** [comment]
Actually, I have no complaints. I like what you do. It's cool, guys 🍀

**Comment by vikrant82** [comment]
@soulless-viewer Do you have an example of retrieving the cookie from the request ? I have a similar usecase, convert cookie to header but can't seem to figure out the lua API.
