### ISSUE TITLE
Problems encountered when opening both 'sequentialMerge' and ‘group’ at the same time

### ISSUE THREAD

**Issue by granty1** [devopsfaith/krakend#330]
**Describe the bug**
My endpoint corresponds to two backends. The first return data contains role_id. the second backend return the role details according to role_id, when grouping is not applicable, this function works normally, but when I group the first backend, there is a problem

**To Reproduce**
1. Configuration used
```
{
      "endpoint": "/findone/{name}",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend/proxy": {
          "sequential": true
        }
      },
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backends": [
        {
          "url_pattern": "/user/{name}",
          "group": "base_info",    // remove this property can work normal
          "encoding": "json",
          "sd": "static",
          "extra_config": {},
          "method": "GET",
          "host": [
            "127.0.0.1:8001"
          ]
        },
        {
          "url_pattern": "/role/{resp0_role_id}",
          "encoding": "json",
          "sd": "static",
          "extra_config": {},
          "method": "GET",
          "group": "role_info",
          "host": [
            "127.0.0.1:8001"
          ]
        }
      ]
    },
```
2. `krakend run -c krakend.json -d` run the krakend-ce
3. `curl http://127.0.0.1:8080/findone/Grant` 
4. results returned:
```
{
  "base_info":{
    "id":1,
    "name":"Grant",
    "role_id":1
  }
}
```

**Expected behavior**
```
{
  "base_info": {
    "id": 1,
    "name": "Grant",
    "role_id": 1,
    "role_info": {
      "id": 1,
      "name": "Administrator"
    }
  }
}
```

**Logs**
in backend's log 
```
[GIN] 2020/02/29 - 14:02:27 | 200 |     226.343µs |       127.0.0.1 | GET      /user/Grant
[GIN] 2020/02/29 - 14:02:27 | 400 |     123.668µs |       127.0.0.1 | GET      /role/{{.Resp0_role_id}}
```

**Additional context**
I check the code in krakend/proxy/merging.go, line124
If grouping is not configured in backend0,
```
data = {
    "id": 1,
    "name": "Grant",
    "role_id": 1
}
```
can get the value of `role_id`

if configured
```
data = {
    "base_info": {
        "id": 1,
        "name": "Grant",
        "role_id": 1
    }
}
```

and can't get value of `role_id` directly

**Comment by kpacha** [comment]
you're right. The feature works very much as you expected at the UT but it doesn't at the integration level. 

I've found there is a bug in the configuration init process and nested params aren't getting parsed properly. so `resp0_foo` works but `resp0_foo.bar` does not. The bad news is it's not fixed by just adding a `\.` at the regex pattern (https://github.com/devopsfaith/krakend/blob/master/config/config.go#L269)

**Comment by granty1** [comment]
Ok,
I think the key issue is in this line
(https://github.com/devopsfaith/krakend/blob/master/config/config.go#L446)

because in this func 
(https://github.com/devopsfaith/krakend/blob/master/config/config.go#L358)
so far, I've only used the following `endpointurlkeyspattern`

I don't know why you modify `simpleurlkeypattern`?
