### ISSUE TITLE
Many questions about SD

### ISSUE THREAD

**Issue by CryBecase** [devopsfaith/krakend#332]
I am a beginner of sd and bloomfilter. I have a lot of questions when researching your source code. Hope to get answers. Thank you!
If some questions are too stupid, I apologize.

1. What does etcd specifically use in the gateway? Why only take backends [0] as the machine?
2. What is the dns srv record used for? How to add srv records locally?
3. Is consul coming to listen to the bloomfilter rpc server? What other effects does consul have?
4. How is rotate bloomfilter better than base bloomfilter? Why is it so designed? Is there anything that rotate can do and base can't?
5. Why use [] [] byte instead of [] byte for rpc input?

**Comment by kpacha** [comment]
@CryBecase don't worry, there are no stupid questions

1- etcd is used as a SD, so it translates service names into addresses. https://etcd.io/docs/v3.4.0/dev-internal/discovery_protocol/
2- dns srv is another SD and it has the same goal: transform a service name into a set of addresses. this is compatible with several SD implementations such as consul, mesos-dns, k8s dns (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#srv-records) or aws route53
3- the bloomfilter service offers the option to register themselves in a consul SD, so it's easier to find them for external clients. that's the only interaction it has with consul.
4- JWT have a TTL and regular bloomfilters do not support delete operations, so rotating the bloomfilter every TTL adds this very desirable feature
5- we choose passing an array of arrays so batches in a single message are possible

**Comment by CryBecase** [comment]
Thank you very much for your reply ^^
