### ISSUE TITLE
HTTP Client Plugin example does not compile

### ISSUE THREAD

**Issue by mikemherron** [devopsfaith/krakend#340]
**Describe the bug**
The HTTP Client Plugin sample provided at https://godoc.org/github.com/devopsfaith/krakend/transport/http/client/plugin does not compile.

**To Reproduce**
1. go version go1.11.13 linux/amd64
2. Copy source from https://godoc.org/github.com/devopsfaith/krakend/transport/http/client/plugin
3. Build with `go build -buildmode=plugin -o client-plugin.so`
4. Get error: `./main.go:33:9: cannot use func literal (type func(http.ResponseWriter, *http.Request)) as type http.Handler in return argument: func(http.ResponseWriter, *http.Request) does not 
implement http.Handler (missing ServeHTTP method)`

**Expected behavior**
It should compile

**Logs**
NA

**Additional context**
The issue can be fixed changing the return func line to wrap the returned function in `http.HandlerFunc`:

```go
return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		fmt.Fprintf(w, "Hello, %q", html.EscapeString(req.URL.Path))
	}), nil
```

Maybe this is related to go version? I understand krakend requires go 1.11 (https://github.com/devopsfaith/krakend-ce#build-requirements) so would expect this to compile.

**Comment by kpacha** [comment]
you're right. the type assignation is missing.

don't worry, it has nothing to do with the go version. It's a problem in the example code I'm fixing right now

thanks for the heads up!
