### ISSUE TITLE
Can inject header from query string

### ISSUE THREAD

**Issue by osmankibar** [devopsfaith/krakend#344]
Hi,

Many of our requests use the authorization header. But some of these put token to query string for authentication.

For example 

https://some-api?access_token="token"

How I can copy query string value to authorization header or how to configure jwt validator to get access token from query string?

**Comment by kpacha** [comment]
JWT validator has 2 token extractors: one for the authentication header and one for the cookie content. there is no way to extract the token from the querystring without using a http handler plugin.

such plugin could check if the access_token querystring is present and copy it to the authentication header. check the documentation for more details and examples: https://godoc.org/github.com/devopsfaith/krakend/transport/http/server/plugin
