### ISSUE TITLE
500 returned in place of 502 or 504

### ISSUE THREAD

**Issue by NoiseByNorthwest** [devopsfaith/krakend#347]
**Describe the bug**
When the backend fails (no valid response) or its response time exceeds the gateway timeout, this is not expected to have the gateway returning a 500.

From the rfc https://www.ietf.org/rfc/rfc2616.txt:

> 10.5.3 502 Bad Gateway
> 
>    The server, while acting as a gateway or proxy, received an invalid
>    response from the upstream server it accessed in attempting to
>    fulfill the request.

> 10.5.5 504 Gateway Timeout
> 
>    The server, while acting as a gateway or proxy, did not receive a
>    timely response from the upstream server specified by the URI (e.g.
>    HTTP, FTP, LDAP) or some other auxiliary server (e.g. DNS) it needed
>    to access in attempting to complete the request.
> 
>       Note: Note to implementors: some deployed proxies are known to
>       return 400 or 500 when DNS lookups time out.

**Comment by x1ah** [comment]
@NoiseByNorthwest Take a look at this: https://github.com/devopsfaith/krakend/issues/288

**Comment by NoiseByNorthwest** [comment]
As explained by @kpacha in #288 this is a design choice which makes sense considering the fact that a lot of logic and several backends can be involved for a given endpoint, far more than it is usually expected for a proxy or a thin gateway.
