### ISSUE TITLE
Backend returning a redirect does not keep headers when following the redirect

### ISSUE THREAD

**Issue by jandillmann** [devopsfaith/krakend#348]
**Describe the bug**
I have a backend that returns a 302 redirect to another endpoint also accessible through the KrakenD API gateway. Both use JWT authentication. KrakenD does not return the 302 redirect to the client, but rather follows the redirect. KrakenD does not include the Authorization header while trying to follow the redirect, resulting in a 401 Unauthorized response.

**To Reproduce**
KrakenD run from the official Docker image using this configuration file:

```
{
  "version": 2,
  "name": "my-api-gateway",
  "endpoints": [
    {
      "endpoint": "/comments/{id}/blog-post",
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "jwk-url": "https://auth.example.org/.well-known/jwks.json",
          "cache": true,
          "issuer": "my-api",
          "disable_jwk_security": false
        }
      },
      "headers_to_pass": {
        "pass": [
          "Authorization"
        ]
      },
      "backend": [
        {
          "url_pattern": "/comments/{id}/blog-post",
          "encoding": "no-op",
          "method": "GET",
          "host": "comments-service"
        }
      ]
    },
    {
      "endpoint": "/blog-post/{id}",
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "jwk-url": "https://auth.example.org/.well-known/jwks.json",
          "cache": true,
          "issuer": "my-api",
          "disable_jwk_security": false
        }
      },
      "headers_to_pass": {
        "pass": [
          "Authorization"
        ]
      },
      "backend": [
        {
          "url_pattern": "/blog-post/{id}",
          "encoding": "no-op",
          "method": "GET",
          "host": "blog-posts-service"
        }
      ]
    }
  ]
}
```

**Expected behavior**
Either reuturn the 302 redirect to the client and let the client handle the redirect, or include the headers from the list of `headers_to_pass` when following a redirect.

**Logs**

```
[GIN] 2020/04/08 - 15:16:49 | 401 |       6.012µs |      172.22.0.1 | GET      /blog-post/2
Error #01: Token not found
[GIN] 2020/04/08 - 15:16:49 | 401 |   79.891029ms |      172.22.0.1 | GET      /comments/1/blog-post
```

**Comment by kpacha** [comment]
redirects in a µservice environment are tricky, because they require the backends to know about the environment and opening the door to cyclic dependencies

that's why the gateway follows the redirects itself. but that redirection has one important condition (from the official http package documentation):

> When following redirects, the Client will forward all headers set on the initial Request except:
> • when forwarding sensitive headers like "Authorization", "WWW-Authenticate", and "Cookie" to untrusted targets. These headers will be ignored when following a redirect to a domain that is not a subdomain match or exact match of the initial domain. For example, a redirect from "foo.com" to either "foo.com" or "sub.foo.com" will forward the sensitive headers, but a redirect to "bar.com" will not.
> • when forwarding the "Cookie" header with a non-nil cookie Jar. Since each redirect may mutate the state of the cookie jar, a redirect may possibly alter a cookie set in the initial request. When forwarding the "Cookie" header, any mutated cookies will be omitted, with the expectation that the Jar will insert those mutated cookies with the updated values (assuming the origin matches). If Jar is nil, the initial cookies are forwarded without change.

**Comment by jandillmann** [comment]
The API follows the JSON:API specification, where the response includes links to the related resources. The backend only has to know the URL of the API gateway (it's the same for all services anyways and set via an environment variable when deploying the service) and the conventions of how the routes are named (which it knows because it follows the JSON:API specification) – for now that's acceptable for what I'm doing in this project.

Can someone with more knowledge in Go explain why the Authorization header is not forwarded despite both domains being the same ("localhost:3000" for development)? According to these lines of code they should be the same, right? https://golang.org/src/net/http/client.go?s=31750:31788

**Comment by alombarte** [comment]
This functionality is only supported on Enterprise
