### ISSUE TITLE
Backend with encoding json cannot handle JSON arrays

### ISSUE THREAD

**Issue by 0xqab** [devopsfaith/krakend#349]
**Describe the bug**
KrakenD cannot handle JSON array responses from backends when the encoding for the backend is set to "json" or "negotiate". Instead, it fails with an error that it cannot unmarshal array into a map. When encoding is set to "text" or "no-op", requests do work.

**To Reproduce**
1. Configuration used
Setup an arbitrary endpoint with `"backend": [ { "encoding": "json" } ]` and have the actual backend return a JSON array instead of a JSON object, i.e. `[{"foo":"bar"},{"foo":"baz"}]` instead of `{"list":[]}`.
2. Steps to run the software
Run a Docker image with `devopsfaith/krakend:1.1.1` and call the endpoint.

**Expected behavior**
JSON arrays are valid JSON, so I expect KrakenD to handle JSON arrays as well as objects.

**Logs**

    [GIN] 2020/04/08 - 16:57:08 | 500 |    378.4322ms |      172.18.0.1 | GET      /api/xxx
    Error #01: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by taik0** [comment]
Hi @0xqab 
You can use the `is_collection` configuration param to indicate that the json response is an array.
Check the documentation here: 
https://www.krakend.io/docs/backends/data-manipulation
