### ISSUE TITLE
JSON data to backend API over the request.

### ISSUE THREAD

**Issue by p000cw** [devopsfaith/krakend#350]
Please need help on this.

How to send json raw data to one of the backend API from the kraken API request - Or accept the json data over body and send the same to one of the API which is configured in the backend.
Any Documentation would be very helpful. or an example kraken.json file.

**Comment by kpacha** [comment]
I think the documentation and the designer show enough details regarding the basic usage of the gateway, but there is also a set of integration tests that could be used as another source of examples. check this out: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L188-L201

**Comment by p000cw** [comment]
What you have pointed out is to pass data over url params this I understood, but what I'm asking is to pass data over raw json. If that is what you have pointed out please let me know what am I missing.

Also an example with respect to this would be very helpful

**The request example** - 

`curl --location --request POST 'http://krakend:8080/user/altar' \`
`--header 'Authorization: Bearer token' \`
`--header 'Content-Type: application/json' \`
`--data-raw '{`
`   "user_id": "1"`
`}'`

**The config json** - 

`{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [
        "*"
      ],
      "expose_headers": [
        "Content-Length"
      ],
      "max_age": "12h",
      "allow_methods": [
        "GET",
        "POST",
        "DELETE"
      ],
      "allow_credentials": true,
      "allow_headers": [
        "Authorization",
        "Content-Type"
      ]
    },
    "github_com/devopsfaith/krakend-opencensus": {
      "sample_rate": 100,
      "reporting_period": 1,
      "exporters": {
        "influxdb": {
          "address": "http://127.0.0.1:8086",
          "db": "krakend"
        }
      }
    }
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "Test API",
  "port": 8080,
  "endpoints": [
    {
      "endpoint": "/user/altar",
      "method": "POST",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/api/v1/backend/u/altar",
          "encoding": "json",
          "extra_config": {},
          "method": "POST",
          "host": [
            "127.0.0.1:5000"
          ],
          "disable_host_sanitize": false
        }
      ],
      "headers_to_pass": [
        "Authorization",
        "Content-Type"
      ]
    },
    {
      "endpoint": "/health",
      "extra_config": {
        "github.com/devopsfaith/krakend/proxy": {
          "static": {
            "data": {
              "status": "OK"
            },
            "strategy": "always"
          }
        }
      },
      "backend": [
        {
          "url_pattern": "/heartbeat",
          "encoding": "json",
          "host": [
            "127.0.0.1:5000"
          ]
        }
      ]
    }
  ]
}`

**Comment by kpacha** [comment]
I think there are some other problems in your scenario... let me show how easy should it be.

krakend.json:
```
{
    "version": 2,
    "host": [ "http://localhost:8080" ],
    "port": 8080,
    "endpoints": [
    {
        "endpoint": "/",
        "method": "POST",         
        "headers_to_pass":[ "Authorization", "Content-Type" ],
        "backend": [
            {
                "url_pattern": "/__debug/"
            }
        ]
    }]
}
```

start the gateway: `./krakend run -d -c krakend.json`

and send a request:
```
curl -id'{"foo":"bar"}' -H'content-type: application/json' localhost:8080
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Krakend: Version 1.1.1
X-Krakend-Completed: true
Date: Fri, 10 Apr 2020 15:46:58 GMT
Content-Length: 19

{"message":"pong"}
```

you'll see the request that hit the backend in your krakend logs:

```
2020/04/10 17:46:58  DEBUG: Method: POST
2020/04/10 17:46:58  DEBUG: URL: /__debug/
2020/04/10 17:46:58  DEBUG: Query: map[]
2020/04/10 17:46:58  DEBUG: Params: [{param /}]
2020/04/10 17:46:58  DEBUG: Headers: map[Accept-Encoding:[gzip] Content-Type:[application/json] User-Agent:[KrakenD Version 1.1.1] X-Forwarded-For:[::1]]
2020/04/10 17:46:58  DEBUG: Body: {"foo":"bar"}
[GIN] 2020/04/10 - 17:46:58 | 200 |     673.214µs |             ::1 | POST     /__debug/
[GIN] 2020/04/10 - 17:46:58 | 200 |    2.456908ms |             ::1 | POST     /
```

notice the body and the header are present in the backend request

**Comment by p000cw** [comment]
Thanks allot. :smile:
