### ISSUE TITLE
Sometimes there is an invalid read on closed body error

### ISSUE THREAD

**Issue by granty1** [devopsfaith/krakend#353]
**Describe the bug**
Sometimes there is an invalid read on closed body error when calling

I've never encountered this problem before, but it's suddenly like this today. Please give me more advice and thanks

**To Reproduce**
1. Configuration used
```
{
  "version": 2,
  "port": 8000,
  "cache_ttl": "3600s",
  "timeout": "3s",
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[TEST]",
      "stdout": true
    }
  },
  "endpoints": [
    {
      "endpoint": "/test",
      "output_encoding":"json",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/api/getAllApis",
          "method": "POST",
          "target": "data",
          "group": "all_data",
          "host": [
              "http://127.0.0.1:8888"
          ]
        },
        {
          "url_pattern": "/api/getApiList",
          "method": "POST",
          "target": "data",
          "group": "list_data",
          "host": [
              "http://127.0.0.1:8888"
          ]
        }
      ]
    }
  ]
}
```
2. Steps to run the software
1. `krakend run -c krakend.json -d`

**Expected behavior**
Calling the `/test` interface will return the result combination of `/getApiList ` and `/getAllApis`

**Logs**
krakend log:

[GIN] 2020/04/13 - 12:55:09 | 200 |    3.603622ms |             ::1 | GET      /test
[GIN] 2020/04/13 - 12:55:15 | 200 |    4.147139ms |             ::1 | GET      /test
Error #01: Post http://127.0.0.1:8888/api/getAllApis: http: invalid Read on closed Body
[GIN] 2020/04/13 - 12:55:15 | 200 |    2.673264ms |             ::1 | GET      /test
Error #01: Post http://127.0.0.1:8888/api/getAllApis: http: invalid Read on closed Body
[GIN] 2020/04/13 - 12:55:16 | 200 |     6.05659ms |             ::1 | GET      /test
Error #01: Post http://127.0.0.1:8888/api/getAllApis: http: invalid Read on closed Body
[GIN] 2020/04/13 - 12:55:16 | 200 |    2.753181ms |             ::1 | GET      /test
Error #01: Post http://127.0.0.1:8888/api/getAllApis: http: invalid Read on closed Body
[GIN] 2020/04/13 - 12:55:17 | 200 |    3.035439ms |             ::1 | GET      /test
Error #01: Post http://127.0.0.1:8888/api/getApiList: http: invalid Read on closed Body

backend server log :
......
[GIN] 2020/04/13 - 12:55:16 | 200 |    3.772641ms |             ::1 | POST     "/api/getApiList"
[GIN] 2020/04/13 - 12:55:16 | 200 |    2.162158ms |             ::1 | POST     "/api/getAllApis"
[GIN] 2020/04/13 - 12:55:17 | 200 |    1.834512ms |             ::1 | POST     "/api/getAllApis"
[GIN] 2020/04/13 - 12:55:17 | 200 |    3.073247ms |             ::1 | POST     "/api/getApiList"
**Additional context**
The first call is normal, and the result merge returns. However, the above error will occur many times in the request, resulting in incomplete response. The `Complete` key in the response header is false, but the log on the back end shows that the request succeeds

**Comment by yuhaifei12** [comment]
I get the same problem. May i ask you how to solved this problem

**Comment by kpacha** [comment]
there should not be more than a single POST request to the backends per endpoint.

**Comment by wchampi** [comment]
I have the same problem: http: invalid Read on closed Body
