### ISSUE TITLE
panic: 'member' in new path '/api/entity/member/assign/:userID' conflicts with existing wildcard ':entityID' in existing prefix '/api/entity/:entityID'

### ISSUE THREAD

**Issue by novalagung** [devopsfaith/krakend#354]
I am working on krakend configuration file. I have two webservices, and I would like to manage both endpoints via one API gateway (krakend) separated by the prefix.

Below is my configuration.

```json
{
  "version": 2,
  "name": "My API Gateway",
  "port": 8080,
  "host": [
    "http://987.654.32.1",
    "http://123.456.789.0"
  ],
  "endpoints": [
    {
      "endpoint": "/api/entity/{entityID}",
      "output_encoding": "no-op",
      "method": "POST",
      "backend": [
        {
          "url_pattern": "/api/entity/{entityID}",
          "encoding": "no-op",
          "host": [
            "http://987.654.32.1"
          ]
        }
      ]
    },
    {
      "endpoint": "/api/entity/member/assign/{userID}",
      "output_encoding": "no-op",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/api/entity/member/assign/{userID}",
          "encoding": "no-op",
          "host": [
            "http://123.456.789.0"
          ]
        }
      ]
    }
  ]
}
```

when I run the krakend using docker run, I got this error info

> panic: 'member' in new path '/api/entity/member/assign/:userID' conflicts with existing wildcard ':entityID' in existing prefix '/api/entity/:entityID'

As far as I understand, seems like the {entityID} on the first endpoint is conflicting with /member/ in the second endpoint, is this behaviour expected? if so then what should I do to make this kind of endpoint definition work?

**Comment by alombarte** [comment]
Please see: https://github.com/devopsfaith/krakend-ce/issues/136#issuecomment-518282622

**Comment by novalagung** [comment]
Hi @alombarte thank you for the info.

Is there any plan to resolve this issue on `krakend-ce` end? without the need to fork the repo and then modify it on my own. maybe changing the router or putting some workaround?

I believe this kind of wildcard endpoints are quite often implemented in REST API design, and also this issue occur because of the limitation of 3rd party lib that is used in the `krakend-ce`.

**Comment by alombarte** [comment]
Hi @ novalagung,

There are no plans to change Gin (which imposes this restriction) in krakend-ce in any near future. Notice that this repo is for the framework only, not the [packaged api gateway we distribute}(https://github.com/devopsfaith/krakend-ce), and it contains several other router implementations and is open to any customization needed, but our official distribution is and will be based on gin.

Long story short, gin is offering us a massive performance, following the line of the rest of the components and middlewares that we have. KrakenD is focused on performance and we are counting new features on nanoseconds, so not being able to declare colliding paths in an API to us is not something that tips the balance. The product has almost 4 years and it's been adopted by thousands, but you'll see a very low number of issues around this. You'll also find a few number of users that use directly the framework and used their own routing (even from major internet players). This is totally fine and expected.

The Krakend framework allows you to build your own gateway changing the router, or even support regular expression-like endpoints, wildcards, and other fancy functionalities. 

Thanks
