### ISSUE TITLE
Always return status 200 in gin router

### ISSUE THREAD

**Issue by donus3** [devopsfaith/krakend#363]
**Describe the bug**
When manually set the proxy.Response.Metadata.Status It does not reflect the setting. For instance

return func(ctx context.Context, request *proxy.Request) (*proxy.Response, error) {
        ...
	return &proxy.Response {
		Data:       resp.Body,
		Metadata: proxy.Metadata{
			StatusCode: http.StatusInternalServerError,
			Headers:    out.Headers,
		},
	}, nil
}

It always the call always return status 200 if the proxy.Proxy is return not nil *proxy.Response.

**To Reproduce**
1. Create a custom proxy and return a custom status code to 401 error
2. Call the API
3. Get status 200

**Expected behavior**
Return status 401

**Comment by donus3** [comment]
fixed in https://github.com/devopsfaith/krakend/pull/362

**Comment by kpacha** [comment]
The status code is not managed in that way. If you want to return a given 40X or 50X status code such as 401, your proxy should return an error implementing this interface:
```
type responseError interface {
	error
	StatusCode() int
}
```
https://github.com/devopsfaith/krakend/blob/master/router/gin/endpoint.go#L146-L149

**Comment by donus3** [comment]
@kpacha I don't know how can I inject the implementation of the `responseError` into the [CustomErrorEndpointHandler](https://github.com/devopsfaith/krakend/blob/master/router/gin/endpoint.go#L28). It accepts `router.ToHTTPError` rather than `responseError`. So, I guest I must inject my custom `router.ToHTTPError`.

**Comment by kpacha** [comment]
here you have a dummy example:

```
type customError struct {
	code    int
	message string
}

func (c customError) StatusCode() int { return c.code }

func (c customError) Error() string { return c.message }

func customProxy(_ context.Context, _ *proxy.Request) (*proxy.Response, error) {
	return nil, customError{
		code:    http.StatusInternalServerError,
		message: "some error description here",
	}
}
```
