### ISSUE TITLE
Is there any way to manipulate endpoint response using Golang?

### ISSUE THREAD

**Issue by nghiant3223** [devopsfaith/krakend#364]
Hello. I am researching the documentation of KrakenD and I find that we can only transform response using Lua script. Is there anyway that I can transform response using Golang?

**Comment by kpacha** [comment]
you have some options:

- plugins: https://www.krakend.io/docs/extending/writing-plugins/
- custom middlewares

**Comment by lukmanralali** [comment]
hi @kpacha, i try to create plugin and successfully loaded.
it work globally, but when i try to put extra config only on specific endpoint it not work.
is this correct behavior? or did i miss something?

thanks for your reply

**Comment by kpacha** [comment]
@lukmanralali handler plugins are global. if you want to activate them just for a set of urls, you should include your own matching strategy.

on the other hand, client plugins are per backend...
