### ISSUE TITLE
Is it possible common bloom filter between multiple krakend pods ?

### ISSUE THREAD

**Issue by Alnyli07** [devopsfaith/krakend#365]
Hi,

We have 3 krakend pods on kubernete clusters. 
Is it possible common bloom filter between these pods ?

If yes, could you share usage example ?

Thanks.

**Comment by kpacha** [comment]
the bloomfilter package exposes a client for remote synchronization of the instances.

check here a working example: https://github.com/devopsfaith/krakend-playground/blob/master/jwt-revoker/main.go

**Comment by Alnyli07** [comment]
Thanks for your reply 
As far as my understanding 
```go
server1 := flag.String("server", "krakend_ce1:1234", "ip:port of the remote bloomfilter to connect to")
server2 := flag.String("server", "krakend_ce2:1234", "ip:port of the remote bloomfilter to connect to")
server3 := flag.String("server", "krakend_ce3:1234", "ip:port of the remote bloomfilter to connect to")

c1, err := client.New(*server1)
c2, err := client.New(*server2)
c3, err := client.New(*server3)

http.HandleFunc("/add/", func(w http.ResponseWriter, r *http.Request) {
		r.ParseForm()
		subject := *key + "-" + r.FormValue(*key)
		c1.Add([]byte(subject))
                c2.Add([]byte(subject))
                c3.Add([]byte(subject))
		log.Printf("adding [%s] %s", *key, subject)
		http.Redirect(w, r, "/", 302)
	})
```
is this the right way to do it ?

Thanks in advance

**Comment by kpacha** [comment]
you're on the right path but remember: the example is not ready for production. you should manage errors and the life cycle of the clients one per each krakend instance running in your cluster.

check the documentation for more details: https://pkg.go.dev/github.com/devopsfaith/bloomfilter/rpc/client?tab=doc
