### ISSUE TITLE
Aggregating similar structured (same schema) objects from different sources

### ISSUE THREAD

**Issue by vidyasagarguduru** [devopsfaith/krakend#367]
Hi,
Is it possible to aggregate similar structured data from multiple end points ? Merge is not useful because it will over write with the last end point response (slow end point). 

I also don't want to use 'Grouping' because it introduces new fields. 

Ex: I am getting this kind of data from 20 systems and want to aggregate using KrakenD 

{
    "build": "b1176-origin/master",
    "date": "2020-05-17.09:03:34",
    "gitBranch": "HEAD",
    "gitSHA": "abcdefg",
    "goVersion": "go1.14.1"
}

Please let me know.

**Comment by alombarte** [comment]
hello,

If you don't want to add a new level, but still you have colliding keys, one option is to rename the fields before the merging operation, using `mapping`: https://www.krakend.io/docs/backends/data-manipulation/#mapping

e.g:
```"backend": [
    {
      "url_pattern": "/",
      "host": [
        "https://system1"
      ],
      "mapping": {
        "build": "system1_build"
      }
    }
  ]
```

**Comment by vidyasagarguduru** [comment]
Thank you for your quick response, but I really don't want change the filed names also because the end system should need to get list of same type of objects. It should be as simple as adding new objects to same type slices. 

I will look into adding a custom plugin or build another service.

**Comment by alombarte** [comment]
If I am understanding you well, you are suggesting something like this:
```
{
"build": ["b1176-origin/master","system20-origin/master","system13-origin/master",...],
"date": ["2020-05-17.09:03:34","2020-05-17.09:03:34","2020-05-17.09:03:34"...],
"gitBranch": ["HEAD","HEAD","HEAD"...],
"gitSHA": ["abcdefg","abcdefg","abcdefg"...],
"goVersion": ["go1.14.1","go1.14.1","go1.12.1"...]
}
```
If that's the case, it looks odd to me as there is no way to guess what element in the slice belongs to each backend. But I don't know the use case, a custom plugin can do the work for you, or maybe a combination of existing tools such as a Lua script.
