### ISSUE TITLE
Create endpoint for sub-resource

### ISSUE THREAD

**Issue by brunofigalves** [devopsfaith/krakend#372]
Hi,

I'm having some problems defining sub-resources endpoints in kraken.json if I only have "endpoint": "/history/visitors/{id}" everything works, but if I add "endpoint": "/history/visitors/{id}/activities" does not work.

`
        {
            "endpoint": "/history/visitors/{id}",
            "method": "GET",
            "backend": [
                {
                    "method": "GET",
                    "host": [
                        "http://192.168.65.3:8082"
                    ],
                    "url_pattern": "/history/visitors/{id}"
                }
            ]
        },
       {
            "endpoint": "/history/visitors/{id}/activities",
            "method": "GET",
            "backend": [
                {
                    "method": "GET",
                    "host": [
                        "http://192.168.65.3:8082"
                    ],
                    "url_pattern": "/history/visitors/{id}/activities"
                }
            ]
        }
`

I can't find any examples in the documentation.

**Comment by kpacha** [comment]
I'm not sure what do you mean with 'does not work'...

```
{
    "version": 2,
    "host": [ "http://localhost:8080" ],
    "port": 8080,
    "endpoints": [
    {
        "endpoint": "/foo/{bar}",
        "backend": [
            {
                "url_pattern": "/__debug/{bar}",
                "group": "foo"
            },
            {
                "url_pattern": "/__debug/{bar}",
                "group": "bar"
            }
        ]
    },
    {
        "endpoint": "/foo/{bar}/foobar",
        "backend": [
            {
                "url_pattern": "/__debug/{bar}/foobar"
            }
        ]
    }
    ]
}
```

this minimal configuration demonstrates that sub-resources are supported

**Comment by alombarte** [comment]
You can use `no-op` if you want to retrieve the backend's response status code
