### ISSUE TITLE
MTLS

### ISSUE THREAD

**Issue by OndraM** [devopsfaith/krakend#374]
**Is your feature request related to a problem? Please describe.**

We use JWT secured endpoints via KrakenD, however, communication between KrakenD and backends is not authenticated.

**Describe the solution you'd like**
We would like to use MTLS (Mutual TLS authentication) for communication between KrakenD and backends.

**Describe alternatives you've considered**
This is possible in KrakenD alternatives:
- https://docs.konghq.com/hub/kong-inc/mtls-auth/
- https://tyk.io/docs/basic-config-and-security/security/tls-and-ssl/mutual-tls/
- https://developers.cloudflare.com/access/service-auth/mtls/

Is it possible to use MTLS via KrakenD? Do you plan such feature? Or is there any alternative approach you would suggest?

Thanks

**Comment by kpacha** [comment]
no, MLTS is not supported out of the box, but there are some alternatives such as:
- oauth2 client credentials: https://www.krakend.io/docs/authorization/client-credentials/
- building a plugin supporting MLTS: https://www.krakend.io/docs/extending/writing-plugins/

**Comment by kpacha** [comment]
#399 adds support for mTLS but between clients and the gateway
