### ISSUE TITLE
JSON Array Object

### ISSUE THREAD

**Issue by NajiMelhaoui** [devopsfaith/krakend#375]
Hello,
My API return an Array of Objects, so i tried to use the :

`"is_collection": true`

but it adds :

```
{
  "collection": [
    {
      ...
    },
    {
      ...
    }
}
```

And i don't want it to change my API response.
How can i achieve that ?
Thank you.

**Comment by kpacha** [comment]
if you don't want to change the response, you can go with `no-op` pipes: https://www.krakend.io/docs/endpoints/no-op/

**Comment by NajiMelhaoui** [comment]
> if you don't want to change the response, you can go with `no-op` pipes: https://www.krakend.io/docs/endpoints/no-op/

Yes, it's perfect, Thank you.
