### ISSUE TITLE
Question: variable from reqeust URL path to body possible?

### ISSUE THREAD

**Issue by Googlom** [devopsfaith/krakend#377]
Hello! I wonder if it's possible to take string variable from URL path of GET request and pass this value to my custom backend handler? I mean:
Request like `GET http://example.com/2b9c0t9ashdfvb2873hbx0023` 
Extract `2b9c0t9ashdfvb2873hbx0023` and pass to backend handler?

**Comment by Googlom** [comment]
Never mind. Found a solution

**Comment by taik0** [comment]
Hi @Googlom 

Can you share the solution you have found for other users with the same requirements?

**Comment by Googlom** [comment]
As I said, I'm using my custom backend handler. Endpoint in `krakend.json` looks like this:
```
{
      "endpoint": "/{hash}",
      "method": "GET",
      . . . 
}
```

With this config **backend handler** receives `proxy.Request` with field `Params` that contains map: 
```
{
      "Hash": "somevalue"
}
```

P.S. why key is capitalized idk.
