### ISSUE TITLE
Subtemplate context & root context

### ISSUE THREAD

**Issue by alexmatsak** [devopsfaith/krakend#380]
Is it possible to access root context(maybe just settings key?) from subtemplate?
Maybe same as doing [helm](https://github.com/helm/helm) with `$` variable

> However, there is one variable that is always global - $ - this variable will always point to the root context. This can be very useful when you are looping in a range and you need to know the chart's release name.

For example:

**partials/header.tmpl**
```
"github.com/devopsfaith/krakend-martian": {
    "header.Modifier": {
        "scope": ["request"],
        "name": "X-Custom-Header",
        "value": {{ .config.some_value }}
    }
}
```
**templates/custom_endpoint.tmpl**
```
{
     ...
    "extra_config": {
        {{ include "secret.tmpl" }}
    },
}
```

**krakend.gojson**
```
    ...
    "endpoints": [
        {{ range $idx, $endpoint := .my_endpoints }}
        {{if $idx}},{{end}}
        {{ template "custom_endpoint.tmpl" $endpoint }}
        {{ end }}
    ]
```

It would be very convenient just to replace settings files for different environments.

**Comment by kpacha** [comment]
yes, it is.

as the documentation says:

```
{{ template "file.tmpl" context }}: Process the Go template file.tmpl passing in its dot ({{ . }}) the context
```

https://www.krakend.io/docs/configuration/flexible-config/

**Comment by alexmatsak** [comment]
@kpachai review the example above please

**$endpoint** value passed as dot context to **templates/custom_endpoint.tmpl**

so i have access only to endpoint config
