### ISSUE TITLE
Response caching not working

### ISSUE THREAD

**Issue by nvlan** [devopsfaith/krakend#382]
Hello,

I have a microservice that for one specific endpoint (/ms/hello/<name>) it replies with a JSON like `{'Hello': name}`. The microservice adds a `Cache-Control` header with `public, max-age:10` values and the backend in kraken has the `"github.com/devopsfaith/krakend-httpcache": {}` configuration as extra_config. However, when I call the kraken endpoint I see that the reply arrives with a `Cache-Control` header that says `public, max-age: 3600` and each time it calls the microservice instead of caching the response JSON.

The endpoint config is as follows:

      {
        "endpoint": "/krakend/saludo/{nombre}",
        "method": "GET",
        "output_encoding": "json",
        "concurrent_calls": 1,
        "backend": [
          {
            "url_pattern": "/devops-test-api-python/hello/{nombre}",
            "encoding": "json",
            "sd": "static",
            "extra_config": {
              "github.com/devopsfaith/krakend-httpcache": {}
            },
            "method": "GET",
            "host": [
              "http://localhost:8081"
            ],
            "disable_host_sanitize": false
          }
        ]
      }

Is this an expected behaviour? How could I properly test/validate if kraken is in fact caching the response?

Thanks a lot, kind regards!

**Comment by kpacha** [comment]
Your issue is related with the backend header not following the [RFC](https://tools.ietf.org/html/rfc7234#section-5.2.2.8). Try again with `Cache-Control: public, max-age=10` (notice the `=` replacing the `:`)
