### ISSUE TITLE
How to properly use "/__stats/" for retrieving metrics?

### ISSUE THREAD

**Issue by rena-ganba** [devopsfaith/krakend#383]
Is there any way for obtaining the metric through "http://localhost:8080/__stats"?

It seems that path is not exist 

NB: I use krakend playground, and I need to retrieve API counter log

**Comment by kpacha** [comment]
at the playground, the metrics should be exposed at port 8090: https://github.com/devopsfaith/krakend-playground/blob/master/krakend/krakend.json#L8
