### ISSUE TITLE
Extra ampersand (&) in the requests to the backend starting with krakend 0.8

### ISSUE THREAD

**Issue by sdepablos** [devopsfaith/krakend#384]
I've already talked with @alombarte regarding this issue, but I leave a report also here.

**Issue**

The problem is that krakend adds an extra ampersand (&) on the query string when passing the request to backends. I.e. we call  `/endpoint?apikey=whatever` on krakend, and the backend receives a `/backend-endpoint?&apikey=whatever`. Note the extra `&` on the query string after the `?`. This should not break any API, but unfortunately it does on the one I'm trying to proxy (and it's an API out of my control). The correct behavior should be calling `/backend-endpoint?apikey=whatever`

**Note**: I understand that `?&` is RFC compliant, but when you hit a wall, being RFC compliant doesn't neither solve the problem nor is any consolation.

**To Reproduce**

I assume krakend is running on port 8080.
1. Create the following config. Note, you can also use the [debug configuration provided on the documentation](https://www.krakend.io/docs/endpoints/debug-endpoint/).
```json
{
  "version": 2,
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "API v1",
  "endpoints": [
    {
      "endpoint": "/v1/Product/List",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/__debug/",
          "host": [
            "http://127.0.0.1:8080"
          ]
        }
      ],
      "querystring_params": [
        "*"
      ]
    }
  ]
}
```
2. Start krakend on debug mode, over port 8080, with the previous config `krakend run -c krakend.json -d -p 8080`
3. Call the endpoint `curl http://localhost:8080/v1/Product/List?apikey=whatever`
4. The log shows `[GIN] 2020/06/25 - 10:11:03 | 200 |      83.893µs |       127.0.0.1 | GET      /__debug/?&apikey=whatever`. Note the query string parameters have an the extra `&`. We receive `?&apikey...` instad of `?apikey...`

This happens with any API, not only with `__debug`, working directly with the binary on Ubuntu or via Docker. **This was introduced in version 0.8**, version 0.7 works as expected (I've been trying different versions with `docker run -p 8080:8080 -v "${PWD}:/etc/krakend/" devopsfaith/krakend:<version> run -d -c /etc/krakend/krakend.json`)

**Expected behavior**

The expected behavior would be the get a call without the `&`, specifically `/__debug/?apikey=whatever`.

**Logs**

Version 1.1 (also 1.0, 0.9 and 0.8)

```
2020/06/25 10:11:03  DEBUG: Method: GET
2020/06/25 10:11:03  DEBUG: URL: /__debug/?&apikey=whatever
2020/06/25 10:11:03  DEBUG: Query: map[apikey:[whatever]]
2020/06/25 10:11:03  DEBUG: Params: [{param /}]
2020/06/25 10:11:03  DEBUG: Headers: map[Accept-Encoding:[gzip] User-Agent:[KrakenD Version 1.1.1] X-Forwarded-For:[127.0.0.1]]
2020/06/25 10:11:03  DEBUG: Body: 
[GIN] 2020/06/25 - 10:11:03 | 200 |      83.893µs |       127.0.0.1 | GET      /__debug/?&apikey=whatever
[GIN] 2020/06/25 - 10:11:03 | 200 |     389.939µs |       127.0.0.1 | GET      /v1/Product/List?apikey=whatever
```

Version 0.7 (works as expected). Note the request does not have the `&?`, only `?`.

```
 DEBUG: Method: GET
 DEBUG: URL: /__debug/?apikey=whatever
 DEBUG: Query: map[apikey:[whatever]]
 DEBUG: Params: [{param /}]
 DEBUG: Headers: map[User-Agent:[KrakenD Version 0.7.1] X-Forwarded-For:[172.17.0.1] Accept-Encoding:[gzip]]
 DEBUG: Body: 
[GIN] 2020/06/25 - 08:18:16 | 200 |     103.745µs |      172.17.0.1 | GET      /__debug/?apikey=whatever
[GIN] 2020/06/25 - 08:18:16 | 200 |  251.358714ms |      172.17.0.1 | GET      /v1/Product/List?apikey=whatever
```

**Comment by kpacha** [comment]
the fix will be included in the next release
