### ISSUE TITLE
Loadbalancing backends by weight

### ISSUE THREAD

**Issue by nvlan** [devopsfaith/krakend#385]
**Is your feature request related to a problem? Please describe.**
Sometimes the devs team wish to do a canary deployment, having a separate backend that answers a small percentage of requests on one endpoint

**Describe the solution you'd like**
We would love to have the ability to configure a "weight" value for each backend configured under a specific endpoint, so that krakend will try to retrieve the content from one backend certain times and the other a smaller amount of times.

**Describe alternatives you've considered**
Adding a loadbalancer layer adds another moving part to the solution and complexity.

**Comment by kpacha** [comment]
I'd say that's already supported by almost all the SD components.
- with static, you can do `["hostA", "hostA", "hostA", "hostA", "hostB"]`  for a 80-20 distribution between hostA and hostB
- with DNS SRV, hosts entries already have a weight assigned

**Comment by nvlan** [comment]
Hi Daniel,

I didn't know that static ends up doing a round-robin if you add the same backend several times. For that to work, should I include the list of hosts in a single backend, or should I add five separate backends in the endpoint each with a single host?

Thanks a lot for your help! Kind regards.

**Comment by kpacha** [comment]
every backend entry under an endpoint will execute a request and all the responses will be merged and returned to the client.

if you want to load balance several instances of the same service, all the hosts should be listed at the same backend

this config exposes 2 endpoints:
```
{
	"version":2,
	"endpoints":[
		{
			"endpoint": "/single",
			"backend": [
				{
					"hosts": ["hostA", "hostB"],
					"url_pattern": "/"
				}
			]
		},
		{
			"endpoint": "/double",
			"backend": [
				{
					"hosts": ["hostA"],
					"url_pattern": "/",
					"group": "a"
				}
				{
					"hosts": ["hostB"],
					"url_pattern": "/",
					"group": "b"
				}
			]
		}
	]
}
```

`/single` will load balance between both instances, hit one and return a single response
`/double` will hit both instances and return a duplicated response under field names `a` & `b`

**Comment by nvlan** [comment]
Cristal clear. Thanks a lot, you've been most helpful!

Kind regards.
