### ISSUE TITLE
Can't Authenticate Via Basic Authentication

### ISSUE THREAD

**Issue by ChristianKlass** [devopsfaith/krakend#388]
Is there an easy way of doing basic authentication (Username and Password) with Krakend? I intend to use Krakend as an API gateway and authenticate itself and return some output via some endpoints.

However, I can't seem to find a way to do basic authentication via Krakendesigner. I can only do OAuth. Is there a way to do this? I'm completely new to this sort of thing, so maybe I am missing out something obvious. I read about writing a plugin to do this, but I have absolutely no idea how to write one from scratch, and this seems like a problem with a fairly obvious and simple solution. Could you (or someone) point me in the right direction?

Thank you.

**Comment by alombarte** [comment]
Hello @ChristianKlass, as per today, KrakenD only supports Basic Authentication in its Enterprise version. The component is not open sourced, but you could implement your own version.

Thanks
