### ISSUE TITLE
Oauth2.0 keycloak integration.

### ISSUE THREAD

**Issue by apuzyrevsky** [devopsfaith/krakend#389]
Hi guys! I am trying to use your product as seems it could handle exactly what I need in mapping, however, I stuck with Oauth2.0 integration. Our API's are using it within keycloak, so I've configured the following setup:

`
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-oauth2-clientcredentials": {
      "endpoint_params": {
        "auth_url": [
          "https://url/auth/realms/realmname/protocol/openid-connect/auth"
        ],
        "callback_url": ["http://url"]
      },
      "client_id": "id",
      "client_secret": "secret",
      "scopes": "profile,email,openid",
      "token_url": "https://url/auth/realms/realmname/protocol/openid-connect/token"
    }
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "clocktower",
  "host": "http://url/",
  "port": 8080,
  "endpoints": [
    {
      "endpoint": "/clocktower/",
      "method": "GET",
      "output_encoding": "json",
      "extra_config": {},
      "backend": [
        {
          "url_pattern": "/links/",
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "extra_config": {
            "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
              "endpoint_params": {
                "auth_url": [
                  "https://url/auth/realms/realm-name/protocol/openid-connect/auth"
                ],
                "callback_url": ["url"]
              },
              "client_id": "id",
              "client_secret": "secret",
              "scopes": "profile,email,openid",
              "token_url": "https://url/auth/realms/realmname/protocol/openid-connect/token"
            }
          },
          "host": ["url"],
          "is_collection": false,
          "target": ""
        }
      ]
    }
  ]
}
`
When I trying to curl my krakend endpoint I receiving in logs following error:
`[GIN] 2020/07/07 - 21:51:19 | 500 |  126.682713ms |             ::1 | GET      /clocktower/
Error #01: Get "http://url/links/": oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized_client","error_description":"Public client not allowed to retrieve service account"}`
It seems like there is something between keykloak, but it is not clear to me where lay this error. 
I would appreciate any help, thank you.

**Comment by kpacha** [comment]
since the pasted config is not a valid json, I guess you tried to remove all the not relevant parts. anyway, the config looks good to me.

I'm not familiar with keycloak, but you can see what's the gateway doing in this test: https://github.com/devopsfaith/krakend-oauth2-clientcredentials/blob/master/http_test.go

**Comment by apuzyrevsky** [comment]
figured it out

**Comment by kpacha** [comment]
@apuzyrevsky can you share the solution for further reference?

**Comment by apuzyrevsky** [comment]
Well, basically we are using keycloak authorization before going to the endpoint, so to the krakend endpoint, we just pass authorization header.
