### ISSUE TITLE
Lua script for proxy doesn't see the path in request

### ISSUE THREAD

**Issue by LeanidM** [devopsfaith/krakend#394]
**In my krakend setup i'm trying to make a check if email in JWT is in the path of called backed. To be sure user is calling the endpoint with his id in the path. I use Lua script, but it return empty path and error when calling url getter**

Url is fine when i change proxy -> router, but then path is also empty

Lua script authorization.lua

function check( request )
    local c = request.load();
	print("Path:" .. c:path());
	print("Url:" .. c:url());
end

**part of configuration file:**

  "endpoints":[
    {
      "endpoint":"/api/{userID}",
      "output_encoding": "no-op",
      "method":"GET",
      "headers_to_pass":[
        "*"
      ],
      "querystring_params":[
        "*"
      ],
      "extra_config": {
        "github.com/devopsfaith/krakend-lua/proxy": {
          "sources":["/etc/krakend/lua/authorization.lua"
          ],
          "pre": "check(request) ",
          "live": true,
          "allow_open_libs": true
        }
     },
      "backend":[
        {
          "host":[
            "http://python:8080"
          ],
          "url_pattern":"/",
          "encoding": "no-op"
        }
      ]
    }
  ]

![image](https://user-images.githubusercontent.com/54355714/87730656-1f925f00-c7d1-11ea-9737-e0565083f923.png)

**Comment by kpacha** [comment]
the url of the request is built just before the backend layer, so move your lua snippet to the `extra_config` of the backend section

```
{
	"endpoints": [{
		"endpoint": "/api/{userID}",
		"output_encoding": "no-op",
		"backend": [{
			"host": [
				"http://python:8080"
			],
			"url_pattern": "/",
			"extra_config": {
				"github.com/devopsfaith/krakend-lua/proxy": {
					"sources": ["/etc/krakend/lua/authorization.lua"],
					"pre": "check(request) ",
					"live": true,
					"allow_open_libs": true
				}
			},
			"encoding": "no-op"
		}]
	}]
}
```
