### ISSUE TITLE
Header x-krakend-completed is false with no-op usage

### ISSUE THREAD

**Issue by 6ecuk** [devopsfaith/krakend#398]
**Describe the bug**
When doing proxy request with no-op and got 204 response status without a body - X-Krakend-Completed is false

**To Reproduce**
Create a request to service which return 204 status response with an empty body.

**Expected behavior**
X-Krakend-Completed is true

**Logs**
If applicable, any logs and debugging information

**Additional context**
Gin router usage

**Comment by kpacha** [comment]
that's the expected behaviour since there is no way for the gateway to know if the response is complete when using `no-op` pipes (since the response body is passed without inspection)
