### ISSUE TITLE
Signer can return token

### ISSUE THREAD

**Issue by huytran96** [devopsfaith/krakend#403]
Hi Krakend, I wanna use Signer to sign token. But I just receive my json payload. Help me!!!!!!!!

kraken.json:
{
  "version": 2,
  "name": "MWGGateway",
  "port": 8080,
  "cache_ttl": "3600s",
  "timeout": "3s",
  "endpoints": [
          {
                "endpoint": "/auth",
                "method": "POST",
                "backend": [
                          {
                                  "url_pattern": "/api/v1/auth",
                                  "method": "POST",
                                  "host": [
                                          "http://10.1.4.68:8095"
                                  ]
                          }
                ],
                "extra_config": {
                        "github.com/devopsfaith/krakend-jose/signer": {
                        "alg": "HS256",
                        "kid": "sim2",
                         "keys-to-sign": ["accessToken"],
                         "jwk-url": "http://10.1.4.68:8095/api/v1/config/jwk/symmetric",
                         "disable_jwk_security": true
                         }
                 }
          }
  ]
}

http://10.1.4.68:8095/api/v1/config/jwk/symmetric:
{
    "kty": "oct",
    "kid": "sim2",
    "k": "AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow",
    "alg": "HS256"
}

http://10.1.4.68:8095/api/v1/auth:
{
    "accessToken": {
        "aud": "MWGServices",
        "exp": 1597334510207,
        "iat": 1597334390207,
        "iss": "MWGUserService",
        "roles": [
            "USER"
        ],
        "sub": "BHX"
    },
    "exp": 1597334510207
}
 
When I call 10.1.4.68:8070/auth Why I'm not receive token.
I receive:
{
    "accessToken": {
        "aud": "MWGServices",
        "exp": 1597334510207,
        "iat": 1597334390207,
        "iss": "MWGUserService",
        "roles": [
            "USER"
        ],
        "sub": "BHX"
    },
    "exp": 1597334510207
}

**Comment by kpacha** [comment]
does the log shows any error loading the jwk file or starting the signer middleware?
