### ISSUE TITLE
Question: Can krakend be configured to foward gRPC requests to local gRPC services running on domain sockets?

### ISSUE THREAD

**Issue by kwtj43** [devopsfaith/krakend#406]
**Is your feature request related to a problem? Please describe.**
Documentation may be clear if this feature is available.

**Describe the solution you'd like**
I would like to configure krackend (via config file) to take gRPC requests over a regular (net) socket and forward them to gRPC services that are running on the same node via unix domain sockets.

**Describe alternatives you've considered**
iptables, nginx, other solutions.

**Additional context**
The motivation for this request is security driven.  I would like to run krackend with less user permissions, run the "backend" services in elevated permissions (i.e. to access hardware) and use linux permissions to secure the backend domain sockets.

**Comment by kwtj43** [comment]
crickets

**Comment by kpacha** [comment]
Sorry for the delay. Hectic weeks.

No, there is no gRPC router for the gateway so far nor consuming backends over local sockets.

**Comment by srix55** [comment]
> Sorry for the delay. Hectic weeks.
> 
> No, there is no gRPC router for the gateway so far nor consuming backends over local sockets.

Any plans for a gRPC router? gRPC seems to be really taking off and other api gateways like tyk are supporting natively. It would be a great add for krakend in my opinion.

**Comment by alombarte** [comment]
No plans yet
