### ISSUE TITLE
Apply httpsecure features (allowed hosts) to selected endpoints

### ISSUE THREAD

**Issue by nvlan** [devopsfaith/krakend#407]
**Is your feature request related to a problem? Please describe.**
We would like to limit the allowed hosts to a single sensitive endpoint, while allowing all other endpoints to be reached freely.

**Describe the solution you'd like**
The possibility to add a krakend-httpsecure block inside the global configs of a single endpoint, instead of in the root level.

**Describe alternatives you've considered**
Currently, I don't have in mind any alternative.

**Additional context**
We are running krakend in Amazon ECS, and if we enable httpsecure, the healthcheck will always fail (the Host header is the IP address of the instance where the container is running).

**Comment by nightmareze1** [comment]
+1

**Comment by kpacha** [comment]
try passing the host header and adding a CEL expression like this `'myHost' in req_headers['Host']` (https://www.krakend.io/docs/endpoints/common-expression-language-cel/)
