### ISSUE TITLE
Getting the value of host from .env file inside a loop

### ISSUE THREAD

**Issue by JGMAGNO** [devopsfaith/krakend#408]
I am having an error regarding access of host value from .env file inside a loop. how do i get the host from other file and setting it inside the loop?

    "endpoints": [
        {{ range .userEndpoint.apis }}
        {
            "endpoint": "{{ .endpoint }}",
            "querystring_params": [ "*" ],
            "method": "{{ .method }}",
            "backend": [
                {
                    "url_pattern": "{{ .backend }}",
                    "host": "{{ .env.node }}",
                    "extra_config": {
                        {{ include "krakend_config.tmpl" }}
                    }
                }
            ],
            "headers_to_pass": [ "Content-Type", "Authorization" ]
        },
        {{ end }}

Error
![image](https://user-images.githubusercontent.com/5405698/93552704-cfd43d80-f9a3-11ea-8ba2-88033cf857f5.png)

**Comment by kpacha** [comment]
I'm not sure, but I'd say you can define variables in your golang templates and use them inside loops... just as suggested at https://golang.org/pkg/text/template/#hdr-Variables

**Comment by JGMAGNO** [comment]
Thanks @kpacha , I was able to call them by adding "$" in before declaring the variable

![image](https://user-images.githubusercontent.com/5405698/94379701-b16cff80-0164-11eb-8e29-e9b16854b9b7.png)
