### ISSUE TITLE
Accessing multiple headers using flexible configuration

### ISSUE THREAD

**Issue by JGMAGNO** [devopsfaith/krakend#414]
I am accessing multiple headers from external file named 'testEndpoint.json', Is there a way that I can get multiple headers and call them inside the loop? I am implementing flexible configuration wherein you can define what headers are you using in your endpoint

krakend.json
![image](https://user-images.githubusercontent.com/5405698/95413938-47700980-095f-11eb-8851-65f4895daeee.png)

testEndpoint.json
![image](https://user-images.githubusercontent.com/5405698/95413955-4f2fae00-095f-11eb-9601-a8b16db9550c.png)

**Comment by kpacha** [comment]
if the var `headers` is an array, you can just marshal it

```
"headers_to_pass": {{ marshal .headers }}
```

**Comment by JGMAGNO** [comment]
ohhh. thanks @kpacha , cheers!
