### ISSUE TITLE
Docker Images on Docker Hub

### ISSUE THREAD

**Issue by neokeld** [devopsfaith/krakend#419]
**Describe the bug**

On Docker Hub, it seems that devopsfaith/krakend:1.2 == devopsfaith/krakend:1 but devopsfaith/krakend:1.2 !== devopsfaith/krakend:1.2.0

**To Reproduce**
Go on https://hub.docker.com/r/devopsfaith/krakend/tags and compare the digests.

**Expected behavior**
devopsfaith/krakend:latest == devopsfaith/krakend:1.2.0 == devopsfaith/krakend:1.2 == devopsfaith/krakend:1
To do it, i think you have to retag devopsfaith/krakend:1.2 and devopsfaith/krakend:1 from devopsfaith/krakend:1.2.0

Thanks a lot !

**Comment by taik0** [comment]
Hi @neokeld !
You are right, that was my mistake. Already fixed!

Thank you!
