### ISSUE TITLE
Error using the querystring.Modifier

### ISSUE THREAD

**Issue by riibeirogabriel** [devopsfaith/krakend#423]
**Describe the bug**
In krakend.json i used the querystring.Modifier to add a param in request, but this error is returned : 
`{<nil> parse: unknown modifier: querystring.Modifier}`
**To Reproduce**
1. Configuration used
![image](https://user-images.githubusercontent.com/33736256/97442204-57e52580-1908-11eb-9fb2-fa31c25fdd42.png)

**Additional context**
It is a bug or i did use the  querystring.Modifier in wrong way?

**Comment by kpacha** [comment]
that modifier is not registered at the krakend-martian middleware. here you have the list of the registered ones: https://www.krakend.io/docs/backends/martian/#all-martian-modifiers-verifiers-and-filters

**Comment by riibeirogabriel** [comment]
I saw this, and i think which this docs doesn't clear to new user, mainly in how usage, maybe it can be improved.

**Comment by riibeirogabriel** [comment]
@kpacha I did follow this tutorial to implement this, in section `Inject query string parameters`, and seems same config.

**Comment by kpacha** [comment]
wow, thanks for the heads up.

you can achieve the same without a modifier. just define your querystring at the `url_pattern` field

```
"url_pattern": "/files?type=projection"
```
