### ISSUE TITLE
krakend check should find conflicting wildcard segments

### ISSUE THREAD

**Issue by nmehlei** [devopsfaith/krakend#427]
**Is your feature request related to a problem? Please describe.**
I'm currently re-working an existing API schema to accommodate the rule that there are no wildcard conflicts, as described at the bottom of https://www.krakend.io/docs/endpoints/creating-endpoints/.

**Describe the solution you'd like**
While this limitation is acceptable, it would be beneficial if `krakend check` could already check for and highlight those conflicts. Otherwise, they might only be noticed at runtime.

**Describe alternatives you've considered**
The alternative would be doing this manually and that is obviously very error-prone.

**Comment by kpacha** [comment]
the `check` command has a flag for that:

```
Aliases:
  check, validate

Examples:
krakend check -d -c config.json

Flags:
  -h, --help              help for check
  -t, --test-gin-routes   Test the endpoint patterns against a real gin router on selected port

Global Flags:
  -c, --config string   Path to the configuration filename
  -d, --debug           Enable the debug
```

so you just need to check your configs with the `-t` flag:
```
krakend check -d -t -c your_config.json
```
