### ISSUE TITLE
Jaeger tracing not working on 1.2.2 

### ISSUE THREAD

**Issue by onwijsbegeerte** [devopsfaith/krakend#429]
**Describe the bug**
Jaeger tracing not working on 1.2.0 on playground repository and possibly/likely also in regular configurations.

**To Reproduce**
``` 
git clone https://github.com/devopsfaith/krakend-playground
docker-compose up
```
- browse to localhost:8080/splash
- navigate to Jaeger http://localhost:16686/
- /Splash trace is missing in Jaeger
- ```krakend_ce_1       | [GIN] 2020/11/16 - 13:44:08 | 200 |    5.782964ms |      172.21.0.1 | GET      /splash```

Change docker-compose to use KrakenD 1.1.1

```
 krakend_ce:
    image: devopsfaith/krakend:1.1.1
```

Repeat steps above, Trace appears in jaeger UI

**Additional context**
I was trying to configure it on Google stack driver, but didn't notice any traces. Went back to the playground configuration to check if I missed something and to see how you configured it. Then I noticed it wasn't working. It seem to only receive traces that hit jaeger itself.

So it could be a bug in 1.2.2 or in the playground configuration of 1.2.2

**Comment by kpacha** [comment]
I just changed the `endpoint` property to set the path

```
"endpoint": "http://jaeger:14268/api/traces"
```

with this change, I'm seeing traces at the jaeger UI from the playground
