### ISSUE TITLE
Integration with AMQP messaging doesn't work

### ISSUE THREAD

**Issue by kevinwell** [devopsfaith/krakend#433]
**Describe the bug**
Backend hosts configured with a `amqp://` protocol throw `panic: invalid host`.

**To Reproduce**
`"host": ["amqp://guest:guest@myqueue.host.com:5672"]`

**Additional context**
I think the problem lies in the regex here https://github.com/devopsfaith/krakend/blob/master/config/uri.go#L10

**Comment by kpacha** [comment]
it looks like your config is missing the `"disable_host_sanitize": true` as suggested at the documentation (https://www.krakend.io/docs/backends/amqp/#consumer)
