### ISSUE TITLE
Integration with Consul DNS

### ISSUE THREAD

**Issue by piomin** [devopsfaith/krakend#455]
**Describe the bug**
I'm running Krakend on macOS. I started Consul on localhost:8600, and my app on a random port (56433). The app is registered in Consul. Here's my configuration in krakend.json for DNS service discovery.
```
    {
      "endpoint": "/employee",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/employees",
          "sd": "dns",
          "host": [
            "employee-service.service.consul"
          ],
          "disable_host_sanitize": true
        }
      ]
    },
```

I configured DNS on macOS to use Consul. For example, when I'm calling my service directly with Consul DNS it works properly:

pminkows@pminkows-mac ~ % curl http://employee-service.service.consul:56433/employees -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to employee-service.service.consul (::1) port 56433 (#0)
> GET /employees HTTP/1.1
> Host: employee-service.service.consul:56433
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 21 Feb 2021 10:42:20 GMT
< Content-Type: application/json
< content-length: 2
< connection: keep-alive
< 
* Connection #0 to host employee-service.service.consul left intact
[]* Closing connection 0

**To Reproduce**
1. Configuration used

Here's my DNS resolver configuration on macOS:

pminkows@pminkows-mac ~ % cat /etc/resolver/consul
nameserver 127.0.0.1
port 8600
search consul
domain consul
2. Steps to run the software
I installed krakend on macOS, and then I'm running it with the following command.
pminkows@pminkows-mac ~ % krakend run -c krakend.json -d

**Expected behavior**
It should use Consul DNS to localize the registered service.

**Logs**
[GIN] 2021/02/21 - 11:01:25 | 500 |     508.483µs |             ::1 | GET      "/employee"
Error #01: no hosts available

**Comment by Atoiebai** [comment]
@piomin got the same trouble , did u solve it?
