### ISSUE TITLE
Deny a field containing a dot

### ISSUE THREAD

**Issue by OSMOSA44** [devopsfaith/krakend#458]
Hello,

Is there a way to deny a field from response backend containing a dot ?

For example, i would like to deny the fields `basic-auth.password`and `basic-auth.username`

```json
{
    "endpointProperties": {
        "authorization.type": "basic",
        "basic-auth.password": "pasword",
        "basic-auth.requireSSL": "true",
        "basic-auth.username": "username"
    }
}
```

Another solution could be to obfuscate the values `password`and `username` by asterisk chain in response to the caller !

```json
{
    "endpointProperties": {
        "authorization.type": "basic",
        "basic-auth.password": "***",
        "basic-auth.requireSSL": "true",
        "basic-auth.username": "***"
    }
}
```

Thanks for your response

Cordialement

**Comment by kpacha** [comment]
at the formater, the dot is used to represent nested elements. If you want to remove or obfuscate values from keys containing a dot you should use a lua script

```
	local responseData = resp:data()
	local prop = responseData:get("endpointProperties")
        prop:set("basic-auth.password", "***")
        prop:set("basic-auth.username", "***")
        responseData:set("endpointProperties", prop)
``` 

cheers
