### ISSUE TITLE
[question] handle parameters not starting with /

### ISSUE THREAD

**Issue by tjamet** [devopsfaith/krakend#46]
Hi,

I am using krakend to serve both api and static content.
As . we are using webpack to generate our static files, it results in paths like:
```
/index.html
/app.<sum>.js
/app.<sum2>.css
/vendor.<sum3>.js
```

and our API endpoint may look like: `/api/<something>`
Ideally, I would like to have configuration file like
```{
  "endpoint": "/api/{path}",
  "method": "GET",
  "backend": [{
    "url_pattern": "/api/{path}",
    "host": [
      "http://api:8080"
    ]
  }]
},
{
  "endpoint": "/{file}",
  "method": "GET",
  "backend": [{
    "url_pattern": "/{file}",
    "host": [
      "http://localhost:8080"
    ]
  }]
```
or
```{
      "endpoint": "/api/{path}",
      "method": "GET",
      "backend": [{
        "url_pattern": "/api/{path}",
        "host": [
          "http://api:8080"
        ]
      }]
    },
    {
      "endpoint": "/app.{file}.css",
      "method": "GET",
      "backend": [{
        "url_pattern": "/app.{file}.css",
        "host": [
          "http://localhost:8080"
        ]
      }]
    },
    {
      "endpoint": "/",
      "method": "GET",
      "backend": [{
        "url_pattern": "/",
        "host": [
          "http://localhost:8080"
        ]
      }]
    }
```
In the first case, I get an error of `panic: wildcard route ':file' conflicts with existing children in path '/:file'`, in the second, I get `ERROR:Fatal error during config init:  Too many output params! input: map[file:<nil>], output: [file]`

The first error is raised by the gin router and it looks like there is nothing much to do about it, for the second error, It seems related to the use of `endpointURLKeysPattern` that includes a leading `/` compared to `simpleURLKeysPattern`.
What would be the impact of always parsing using `simpleURLKeysPattern` ?

**Comment by kpacha** [comment]
Hi!

Removing the `endpointURLKeysPattern` and using the `simpleURLKeysPattern` as you suggest it's ok.

This distinction was added in order to enforce a 'proper' RESTful resource naming, but I'm no longer sure that's the right thing to do...
