### ISSUE TITLE
Configure Backend Graphql

### ISSUE THREAD

**Issue by benjamingb** [devopsfaith/krakend#461]
I am using a **graphql** backend but no response, I get the message of

```
[GIN] 2021/03/12 - 02:51:22 | 500 | 1m0s | 192.168.10.71 | POST "/ shop"
Error # 01: context deadline exceeded
```

What would be the correct configuration?

**# krakend.json**
```
{
  "version": 2,
  "name": "API Gateway Keeper v1",
  "port": "8080",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    }
  },
  "endpoints": [
    {
      "endpoint": "/shop",
      "method": "POST",
      "output_encoding": "no-op",
      "extra_config": {},
      "backend": [
        {
          "url_pattern": "/graphql",
          "encoding": "no-op",
          "sd": "static",
          "method": "POST",
          "extra_config": {},
          "host": ["http://192.168.10.71:7060"],
          "disable_host_sanitize": true
        }
      ],
      "timeout": "60000ms"
    }
  ]
}

```
UPDATE 
This error occurs when the microservice is on the same pc as krakend, I am using dockers,
do they have to be on separate servers?

**Comment by alombarte** [comment]
Hello @benjamingb , you can have krakend and the microservices anywhere as long as there are connectivity and visibility between them. This is likely the issue you are facing right now as after 1 minute the message "context deadline exceeded" (timeout) comes in. Check your docker-compose or similar file (or share it with us)

**Comment by benjamingb** [comment]
Reinstall docker and it worked!
