### ISSUE TITLE
proxy metadata and cookie

### ISSUE THREAD

**Issue by tjamet** [devopsfaith/krakend#48]
Hi,

Using Krakend to serve html content, my servers often send `Set-Cookie` headers.
I often have response headers like:
```
Set-Cookie: cookieName=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Set-Cookie: cookieName2=value; Path=/; Max-Age=3600
```
To forward those cookies, I am using the `Response.Metadata` field of `proxy/proxy.go`, joining cookie headers using:
```
var response proxy.Response
response.Metadata["Set-Cookie"] = strings.Join(resp.Headers["Set-Cookie"], ",")
```
and setting the header back to  with
```
for header, value := range response.Metadata {
    c.Header(header, value)
}
```

The problem with this approach is that having a `,` in the `Set-Cookie` header, only the first cookie is forwarded.

I was thinking of updating the `Metadata` type to either `[]string` to match the `http.Header` type or `interface{}` to allow any users to store metadata in any format.

What do you think?

**Comment by kpacha** [comment]
Hi @tjamet !

you've made a very good point: the `Metadata` field is not covering the case of multiple headers with the same name.

regarding the two proposed options, the first one seems the easiest to implement but I'm afraid we'll hit the same wall when adding a new transport protocol... 🤔 

Maybe we should create a `Metadata` struct, so we can replace the internal types without changing the signatures and interfaces, just the implementations.

```
type Metadata struct{
    Headers map[string][]string
}
```

**Comment by tjamet** [comment]
that's  a good idea, do you think interesting to add an `Extra interface{}` field to allow framework users to use it to store what ever they want?

**Comment by kpacha** [comment]
Thanks!
