### ISSUE TITLE
Question: Is it possible to return mock/fake json responses to an endpoint?

### ISSUE THREAD

**Issue by crjacinro** [devopsfaith/krakend#486]
I am exploring the capabilities of this library to a golang backend and would like to ask if its possible to setup an environment in which an endpoint directly returns sample json response / models (either from json files or a go object model). In this mode, the endpoint returns immediately with the sample models and will not call all the other backend services, and will not do any aggregation or merge for that endpoint. 

Thank you

**Comment by x1ah** [comment]
KrakenD provide **Static Proxy**, you can found it at https://www.krakend.io/docs/endpoints/static-proxy/
