### ISSUE TITLE
About the pricing

### ISSUE THREAD

**Issue by mytototo** [devopsfaith/krakend#6]
Hi,

I just found your project and it looks very interesting.
I have a question though: does the pricing on the feature page apply to the open-source version too? I mean, with the open-source version can we have as much nodes as we need or this only apply for the cloud? It's a bit confusing.

Also, can we handle consumers and give them credentials to consume our endpoints?

Thanks.

**Comment by friedcalamari** [comment]
Hi @mytototo, thank you!

The open-source version is free and you can do as many installs as you want but between them there won't be a cluster, so  you will need to manually manage every installation. The paid version works forming a cluster and the configuration is centralised in the cluster manager. The KrakenD works by installing the service on premises or in the cloud, but your cloud. There is no option that we host your own API like a SaaS yet.

As per the credentials, the KrakenD will pass the headers so your current mechanisms validate the requests. The KrakenD is not an OAuth server but can be integrated with any other.

Feel free to ask any other question you might have, hope you enjoy the product!
