### ISSUE TITLE
Possibility - backend query within a backend query

### ISSUE THREAD

**Issue by rgogulakrishnan** [devopsfaith/krakend#89]
Hi,

Is it possible to run a backend query within an another backend query..? 
For example, 
API Endpoint 
   - Service A
         -  Response received, having a for loop, iteration happens say 5 IDs, so 5 requests
                - call Service B for ID 1
                - call Service B for ID 2
                - call Service B for ID 3
                - call Service B for ID 4
                - call Service B for ID 5
         - Map and do final response manipulation
  - Service C
       - Response recieved

Finally manipulate response for all and sends back the response.
Not sure if this kind of support available. Documentation has stuff relatively straight forward like just call 2 or 3 services one by one..

**Comment by alombarte** [comment]
Hello @rgogulakrishnan,

KrakenD does not support chaining API calls (use the responses to call other services). This kind of orchestration is a pattern that belongs more to an ESB solution than a Gateway.

At a technical level it would be perfectly doable, but it does not fit in the gateway pattern so we don't support it now or in the future as a KrakenD out of the box feature.

And finally, in the API gateway the services are not called one by one, but all at once. Chaining services would also mean a drop in performance.

Any additional clarifications please let me know.

Thanks!

**Comment by rgogulakrishnan** [comment]
Thanks.. Just wanted to confirm..
